### ISSUE TITLE
请问在centos上如何做开机启动？

### ISSUE THREAD

**Issue by sifanx** [dushixiang/next-terminal#100]
你好，我在 /etc/rc.d/rc.local 里添加脚本，只能实现 guacamole-server 自启，next-terminal 部分的自启代码无效，有什么办法可以实现开机自启吗？

**Comment by dushixiang** [comment]
制作成系统服务的方式，也就是systemd。

**Comment by sifanx** [comment]
用systemd制作成服务的方式可以自启动了，但是有个新问题，脚本里我用"/root/next-terminal/next-terminal"网站打不开，发现端口号从80变成其它的了，再执行发现端口又会随机变化，如果用"cd /root/next-terminal/ && ./next-terminal"启动，网页就能打开，端口也是默认80.

![image](https://user-images.githubusercontent.com/42561369/111094566-82adde80-8576-11eb-89f3-166a0436812c.png)
![image](https://user-images.githubusercontent.com/42561369/111094592-90fbfa80-8576-11eb-993b-080b4599ca14.png)
![image](https://user-images.githubusercontent.com/42561369/111094620-9f4a1680-8576-11eb-9c6e-73aedd1bcd92.png)

**Comment by dushixiang** [comment]
需要指定 WorkingDirectory

**Comment by dushixiang** [comment]
也就是next-terminal所在文件夹，要读取配置文件

**Comment by sifanx** [comment]
哦，好的，谢谢，我配置一下看看
