### ISSUE TITLE
可否给RDP添加通过隧道连接的功能

### ISSUE THREAD

**Issue by z1073** [dushixiang/next-terminal#103]
我机房里的windows服务器远程都是通过SSH[转发](https://www.coder.work/article/6800490)RDP端口，一些远程工具也带SSH网关功能,这样连接更安全,next-terminal能否也添加类似功能呢？

![mx](https://user-images.githubusercontent.com/50789523/111273388-b835f300-866e-11eb-8a30-49a4e3bd856a.png)

**Comment by dushixiang** [comment]
不支持此功能。
