### ISSUE TITLE
Apache 反代至子目录时 login 返回 Method Not Allowed

### ISSUE THREAD

**Issue by AndroidOL** [dushixiang/next-terminal#107]
ProxyPass /nt/ http://127.0.0.1:port/
    ProxyPass /info http://127.0.0.1:port/
    ProxyPass /overview http://127.0.0.1:port/
    ProxyPass /login http://127.0.0.1:port/

    ProxyPassReverse /nt/ http://127.0.0.1:port/
    ProxyPassReverse /info http://127.0.0.1:port/
    ProxyPassReverse /overview http://127.0.0.1:port/
    ProxyPassReverse /login http://127.0.0.1:port/

例如子目录使用的是 xx.com/nt/，登陆时 login 返回 HTTP 200，但内容是 {"code":405,"message":"Method Not Allowed"}，看了 FAQ 是 nginx 的例子，请问 Apache 应该如何配置

**Comment by dushixiang** [comment]
我没使用过Apache这个http服务器，无法回答你的问题。

**Comment by AndroidOL** [comment]
> 我没使用过Apache这个http服务器，无法回答你的问题。

感谢回复，我试试 nginx

**Comment by AndroidOL** [comment]
> 我没使用过Apache这个http服务器，无法回答你的问题。

你好，试了下 nginx 好像也没办法反代到二级目录下，看上去类似于 chfs 的 Web 页面，是不是只能用子域名代替了呢。

**Comment by dushixiang** [comment]
不支持二级目录方式。
