### ISSUE TITLE
RSA 证书登录提示 服务器密码验证失败

### ISSUE THREAD

**Issue by AndroidOL** [dushixiang/next-terminal#108]
1. 证书没错，格式如下：
---- BEGIN PRIVATE KEY ----
Comment: rsa 8192-111417
xxxx证书内容xxxx
---- END PRIVATE KEY ----
2. 私钥没错
3. 用户名没错，有且只有一个用户名（小写）
4. XShell 可以正常登录，系统为 Ubuntu 和 OpenWRT

请问有日志可以提供么，Docker 部署的。

**Comment by AndroidOL** [comment]
不好意思，找到日志了，提示“创建SSH客户端失败：ssh: no key found”

**Comment by AndroidOL** [comment]
目前用的最新版本，看见之前提的 issue 但是没发现有帮助

https://github.com/dushixiang/next-terminal/issues/5

**Comment by dushixiang** [comment]
我测试的无法复现这个问题，可以正常访问。

**Comment by TianmoTTT** [comment]
我也碰见了ubuntu 的虚拟机，用的vnc sever,5900的端口，也是提示认证失败。
