### ISSUE TITLE
希望增加 https 支持

### ISSUE THREAD

**Issue by AndroidOL** [dushixiang/next-terminal#111]
反向代理可以实现，我了解，但未来能否在页面或者 docker 中原生支持 https 呢，谢谢。

**Comment by dushixiang** [comment]
反向代理实现https是一种非常常见的方式，docker内部开启https需要配置开放相应的端口，较为复杂，为什么会有这种需求呢？

**Comment by AndroidOL** [comment]
了解，端口太多，人太懒导致产生该问题的。
