### ISSUE TITLE
RDP在浏览器中显示不全

### ISSUE THREAD

**Issue by TianmoTTT** [dushixiang/next-terminal#122]
使用rdp登录到windows桌面时候浏览器的右边和下边的滑动条会挡住页面的显示可以调整一下吗

**Comment by dushixiang** [comment]
请描述一下你使用的操作系统，浏览器，分辨率以及是否缩放。

**Comment by TianmoTTT** [comment]
windows 10,360浏览器极速版，没有缩放100%的，系统分辨率2k。

**Comment by TianmoTTT** [comment]
![Uploading 微信图片_20210322100047.png…]()

**Comment by TianmoTTT** [comment]
![f0856e20f37955a3657ae0078ad2850](https://user-images.githubusercontent.com/32138819/111968432-1a419d00-8b34-11eb-89ed-9ffa098a97d3.png)

另外 我使用vnc 连接ubuntu上的 vnc server 一直提示认证失败 但是实际上账号密码没有错误   正常的vnc 会提示保存秘钥是不是这个原因啊
![f02a313c613cf9405dfb246ea6a5df8](https://user-images.githubusercontent.com/32138819/111968425-17df4300-8b34-11eb-9dbf-0c259327409f.png)

**Comment by dushixiang** [comment]
你把书签栏隐藏之后再试下，我怀疑是这里的问题。

**Comment by TianmoTTT** [comment]
还是不行，我试过全屏，但是还是不行，也隐藏了书签栏。

**Comment by dushixiang** [comment]
![image](https://user-images.githubusercontent.com/17633733/112078972-515a9180-8bba-11eb-97d9-a1b8a22a74a1.png)
这是我测试的截图

**Comment by TianmoTTT** [comment]
好的，我回去再试试，域名不隐藏一下？  会不会是因为你用的win7，部署在debian10上的 ，字体的软件没装，还有你的https的证书和key都是pem结尾的？ 我的是.crt和 .key 我取消注释后还是http，端口变成随机的了。

**Comment by dushixiang** [comment]
这个是演示站点。

**Comment by TianmoTTT** [comment]
好吧

**Comment by TianmoTTT** [comment]
![80eda2e03e157072168336a60f55ca7](https://user-images.githubusercontent.com/32138819/112089347-6cce9800-8bcc-11eb-903c-990ba4665c37.png
我找到原因了，启用了浏览器的插件，关掉了就可以了，我。。。。。。。。。

**Comment by TianmoTTT** [comment]
还有个问题就是https 没有自动启动啊还是http, 设置了证书和keyh,还是不行啊

**Comment by dushixiang** [comment]
建议使用nginx反向代理实现https

**Comment by TianmoTTT** [comment]
我有使用 nginx反代，但是链接好像有问题，一个显示正在链接

**Comment by dushixiang** [comment]
请参考faq 配置

**Comment by TianmoTTT** [comment]
搞定 希望作者越来越好

**Comment by dushixiang** [comment]
谢谢夸奖，有兴趣可以pr或者点个star持续关注，后面还会继续更新功能。

**Comment by TianmoTTT** [comment]
好的
