### ISSUE TITLE
是否有考虑实现一下RemoteApp功能？

### ISSUE THREAD

**Issue by wy281704862** [dushixiang/next-terminal#125]
RemoteApp是rdp的功能，Guacamole也支持。
我这边有访问数据库的需求，考虑是否可以通过RemoteApp调用服务器上面的navicat来实现？

**Comment by dushixiang** [comment]
此功能有的，添加rdp资产的时候可以在右侧看到选项。

**Comment by wy281704862** [comment]
嗯，不好意思，之前没注意，现在看到了。另外是否可以实现一下登录需要短信验证码？验证码直接调接口，接口自己封装实现。

**Comment by wy281704862** [comment]
> 此功能有的，添加rdp资产的时候可以在右侧看到选项。

嗯，不好意思，之前没注意，现在看到了。另外是否可以实现一下登录需要短信验证码？验证码直接调接口，接口自己封装实现。

**Comment by dushixiang** [comment]
短信服务每一个平台的接口都不相同，因此并未实现，而是通过totp来实现多重因素验证。

**Comment by dushixiang** [comment]
> > 此功能有的，添加rdp资产的时候可以在右侧看到选项。
> 
> 嗯，不好意思，之前没注意，现在看到了。另外是否可以实现一下登录需要短信验证码？验证码直接调接口，接口自己封装实现。

短信服务每一个平台的接口都不相同，因此并未实现，而是通过totp来实现多重因素验证。

**Comment by wy281704862** [comment]
> > > 此功能有的，添加rdp资产的时候可以在右侧看到选项。
> > 
> > 
> > 嗯，不好意思，之前没注意，现在看到了。另外是否可以实现一下登录需要短信验证码？验证码直接调接口，接口自己封装实现。
> 
> 短信服务每一个平台的接口都不相同，因此并未实现，而是通过totp来实现多重因素验证。

短信接口可以自己去实现，你可以做一个灵活的。比如： 配置文件里面定义一个url，然后你发短信就post一个手机号码和验证码参数给这个url就可以了。其他的短信发送由这个接口去实现。

**Comment by dushixiang** [comment]
> > > > 此功能有的，添加rdp资产的时候可以在右侧看到选项。
> > > 
> > > 
> > > 嗯，不好意思，之前没注意，现在看到了。另外是否可以实现一下登录需要短信验证码？验证码直接调接口，接口自己封装实现。
> > 
> > 
> > 短信服务每一个平台的接口都不相同，因此并未实现，而是通过totp来实现多重因素验证。
> 
> 短信接口可以自己去实现，你可以做一个灵活的。比如： 配置文件里面定义一个url，然后你发短信就post一个手机号码和验证码参数给这个url就可以了。其他的短信发送由这个接口去实现。

此功能太过定制化，暂时不会做此功能。
