### ISSUE TITLE
原生SSH中，文件管理的弹窗会被挡住

### ISSUE THREAD

**Issue by if1y** [dushixiang/next-terminal#126]
一切弹窗都会被`会话管理`挡住，包括但不限于`文件上传`、`确认删除`、`创建文件夹`
问题是在`原生SSH`中出现的，为了展示问题，截图时使用的是`默认`连接模式
![image](https://user-images.githubusercontent.com/32222791/113297766-9e163900-932d-11eb-93e8-eb26a9dfdc97.png)

**Comment by dushixiang** [comment]
问题已经定位，将在下个版本进行修复。

**Comment by dushixiang** [comment]
v0.4.1 修复了这个问题
