### ISSUE TITLE
更新后二次验证无法通过

### ISSUE THREAD

**Issue by z775729168** [dushixiang/next-terminal#129]
你好
我使用docker安装的，原来的版本是0.2.7，现在升级到0.3.4
按照说明在升级前复制了drive，recording和next-terminal.db
在更新后，可以通过密码验证，但输入二次验证，两次左右，都提示错误
我再把版本退回老的0.2.7，还是同样的问题
尝试把密码重置，0.2.7好像没有这个指令，换到0.3.4重置密码，但是现在admin/admin不能登录，原来的密码也不能登录
我觉得我已经丢了一些东西……还需要提供log吗？
谢谢

**Comment by dushixiang** [comment]
目前尚未提供重置二次验证的功能，可以先进入数据库把`users`表的`totp_secret`字段设置为null或空字符串。

**Comment by z775729168** [comment]
谢谢回复

**Comment by dushixiang** [comment]
新增了重置totp的命令 https://github.com/dushixiang/next-terminal/blob/master/docs/faq.md
totp无故验证失败很有可能是docker的时间不同步导致的，建议检查一下docker容器内部的时间。

**Comment by z775729168** [comment]
非常感谢
