### ISSUE TITLE
普通用户为什么可以看到所有用户，这个设计不合理

### ISSUE THREAD

**Issue by mapengXM** [dushixiang/next-terminal#133]
普通用户为什么可以看到所有用户，这个设计不合理
![image](https://user-images.githubusercontent.com/19262062/115518131-6eb67480-a2ba-11eb-8698-1454dadbb72b.png)

**Comment by dushixiang** [comment]
建议更新到最新版本 v0.3.5

**Comment by mapengXM** [comment]
这就是0.4.0版本
![image](https://user-images.githubusercontent.com/19262062/115548177-c2848600-a2d9-11eb-96b8-4a01b9f85421.png)

**Comment by dushixiang** [comment]
正常情况下普通用户是没有用户管理的权限的，相应的菜单也不会显示，但是在共享资产的时候目前是可以查询到全部的用户的，你这里应该是切换了用户，在原来的基础上刷新的页面吧。
另外即使可以看到用户，但删除用户，重置密码也是没有权限的。
我在考虑普通用户是否只能查询到普通用户才对？

**Comment by mapengXM** [comment]
![image](https://user-images.githubusercontent.com/19262062/115639245-af5bcf80-a346-11eb-8c08-58b00743d6a8.png)

**Comment by ilay1678** [comment]
确实有这个问题

**Comment by dushixiang** [comment]
下个版本普通用户只允许查看普通用户列表
