### ISSUE TITLE
密码和私钥等应该只在添加时显示

### ISSUE THREAD

**Issue by ilay1678** [dushixiang/next-terminal#136]
出于安全性考虑，建议查看和编辑页面不予展示

**Comment by ilay1678** [comment]
> 感觉编辑的功能也是需要的

编辑时反正都要修改了，没必要留着吧。

**Comment by ilay1678** [comment]
编辑时如果传过来值，则修改保存到数据库，如果不传值，就不修改

**Comment by dushixiang** [comment]
> > 感觉编辑的功能也是需要的
> 
> 编辑时反正都要修改了，没必要留着吧。

有点道理，或许做成使用登录密码或者二次认证之后才能查看更好吧

**Comment by ilay1678** [comment]
其实都能直接登录到服务器了，改密码创建用户什么的都能实现，这个功能确实不是很有必要。
感觉应该加个禁用命令功能，比如禁止某个用户组执行某个命令

**Comment by dushixiang** [comment]
> 其实都能直接登录到服务器了，改密码创建用户什么的都能实现，这个功能确实不是很有必要。
> 感觉应该加个禁用命令功能，比如禁止某个用户组执行某个命令

说的也是。禁用命令的功能想不到好的办法来实现，因为可以通过把命令写入脚本来执行，或者输入某几个字符之后按方向键来调整命令，没有办法获取到ssh会话最终要执行的命令是什么。

**Comment by althyman** [comment]
> > > 感觉编辑的功能也是需要的
> > 
> > 
> > 编辑时反正都要修改了，没必要留着吧。
> 
> 有点道理，或许做成使用登录密码或者二次认证之后才能查看更好吧

有以下场景：我多台内网server使用同一个授权（也就是用户名密码相同）登录，后续因为安全要求，我使用批量工具对所有的密码进行了变更，此时如果不能编辑授权的话，那我就需要重新创建授权，然后一台一台的修改资产的引用，也比较麻烦。
建议保留编辑功能，添加二次验证就可以了。二次验证的安全性应该可以了吧。
