### ISSUE TITLE
资产服务器的SSH启用了两步认证，“接入”时直接报“服务器密码验证失败”

### ISSUE THREAD

**Issue by oooh-name** [dushixiang/next-terminal#137]
使用了next-terminal 的 docker 容器，
资产服务器为SSH启用了两步认证：google-authenticator，但是“接入”时直接报“服务器密码验证失败”。

**Comment by dushixiang** [comment]
两步认证和访问资产没有关系的，请确认一下密码是否正确。

**Comment by oooh-name** [comment]
> 两步认证和访问资产没有关系的，请确认一下密码是否正确。

不使用密码，SSH登录使用密钥+密钥密语+TOTP，进入容器内部使用 ssh 命令 ssh -i id_rsa -p 22 user@host 是正常提示需输入密语和TOTP的：
`Enter passphrase for key 'id_rsa':
Verification code:`
而web那边使用原生模式接入时显示：
`Trying to connect to the server ...
ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain`

密钥，授权账户，端口，主机这四个确认和web画面设置的内容是一样的。

**Comment by oooh-name** [comment]
资产服务器的sshd_config里面设置了 `PasswordAuthentication no`
