### ISSUE TITLE
批量命令执行报错

### ISSUE THREAD

**Issue by iLay1678** [dushixiang/next-terminal#14]
DOMException: Failed to construct 'WebSocket': The URL '/ssh?X-Auth-Token=xxxxxxxx' is invalid

**Comment by dushixiang** [comment]
请问一下版本和浏览器是什么？

**Comment by iLay1678** [comment]
版本0.3，浏览器chrome 87.0.4280.88

**Comment by dushixiang** [comment]
我测试了win和mac都没有发现这个问题，普通模式能连接吗？

**Comment by iLay1678** [comment]
普通模式是可以连接的

**Comment by dushixiang** [comment]
是使用密钥认证的吗？

**Comment by iLay1678** [comment]
单独密钥 或单独密码的服务器，用批量执行也不行

**Comment by dushixiang** [comment]
建议更新v0.0.5版本后重新看下，增加日志输出。

**Comment by iLay1678** [comment]
是前端报错，后端没报错
![Snipaste_2021-01-09_09-03-27](https://user-images.githubusercontent.com/7021399/104078540-a5abd180-5259-11eb-8bb7-272b80d5d958.png)

**Comment by dushixiang** [comment]
v0.0.6版本修复了这个问题。
