### ISSUE TITLE
windows远程桌面失败

### ISSUE THREAD

**Issue by dreamskr** [dushixiang/next-terminal#142]
您好，windows输入帐号密码后，提示如下图
![image](https://user-images.githubusercontent.com/43511466/118497737-dd012200-b714-11eb-8fa7-60b31a53833d.png)

点重新连接后，又出现如上图，请问是安装过程有问题吗？

**Comment by TianmoTTT** [comment]
你用mstsc登录正常吗？ 我只碰见过用ubuntu远程的时候出这个提示

**Comment by dushixiang** [comment]
> 您好，windows输入帐号密码后，提示如下图
> ![image](https://user-images.githubusercontent.com/43511466/118497737-dd012200-b714-11eb-8fa7-60b31a53833d.png)
> 
> 点重新连接后，又出现如上图，请问是安装过程有问题吗？

账号或密码不正确

**Comment by dreamskr** [comment]
mstsc能正常登录，密码也是对的，输入帐号密码后，刚进入桌面，马上跳出这个提示

**Comment by dushixiang** [comment]
> mstsc能正常登录，密码也是对的，输入帐号密码后，刚进入桌面，马上跳出这个提示

win7或者 win server 2008的配置请参考 FAQ
https://github.com/dushixiang/next-terminal/blob/master/docs/faq.md
