### ISSUE TITLE
docker 使用 docker-compose 卡主了

### ISSUE THREAD

**Issue by RBeyond** [dushixiang/next-terminal#143]
![image](https://user-images.githubusercontent.com/78027896/118793191-f350de80-b8ca-11eb-8053-9640a25c4d67.png)
卡在上面截图位置了，不执行了

**Comment by wojiushixiaobai** [comment]
使用 
```bash
docker-compose up -d
```
在后台运行，没有 -d 的话，会一直在前台刷新 log。详情可以参考 compose 的官方使用说明

**Comment by yanhuanyu** [comment]
求助一下 启动了容器但是访问web端口拒绝连接。
![image](https://user-images.githubusercontent.com/37525283/128284196-3036560b-2453-44e1-9273-1581adf6a588.png)
![image](https://user-images.githubusercontent.com/37525283/128284255-f68330d2-8ee1-4d50-b1bf-88f4ae0906df.png)

**Comment by RBeyond** [comment]
确认下系统访问的端口是监听
用命令&nbsp; lsof -i:8088 或其他端口
然后在看下系统防火墙是否可以了，可关闭直接关闭，不能关闭需要把端口加入到允许访问，如果是阿里云或第三方服务商需要在安全组加入端口才能外网访问
https://blog.csdn.net/DH_SIR/article/details/79244059&nbsp; 链接为查看是否开启防火墙




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dushixiang/next-terminal"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月5日(星期四) 中午11:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dushixiang/next-terminal] docker 使用 docker-compose 卡主了 (#143)





 
求助一下 启动了容器但是访问web端口拒绝连接。
 
 
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dushixiang** [comment]
已更新 docker-compose 安装文档。
https://next-terminal.typesafe.cn/document/#docker-%E5%AE%89%E8%A3%85
