### ISSUE TITLE
关于几个功能改进建议

### ISSUE THREAD

**Issue by dreamskr** [dushixiang/next-terminal#144]
首先特别感谢作者提供这么好这么实用的功能，根据使用情况提出几点建议，希望能改进

1.**资产列表**：添加显示IP和点击排序的功能；在操作字段，把高频使用的编辑和复制直接显示出来（或点击资产名称弹出编辑框）；导入时允许导入标签，另外有时无法导入；有Kubernetes协议，但查询条件的下拉列表中没有这个协议，会话审计的查询条件也没有这个协议；增加状态这个字段的查询条件。
2.**指令列表**：把高频使用的编辑直接显示出来（或点击指令名称弹出编辑框）；添加telnet的支持，华为、H3C等路由器交换机经常要执行一批命令。
3.**在线会话**和**历史会话**：增加显示主机IP，并允许排序。
4.**计划任务**：把高频使用的编辑直接显示出来（或点击任务名称弹出编辑框）。
5.**系统设置**：远程windows桌面时老是自动重连，建议在安装时，“禁用字形缓存”默认开启。
6.**关于日期时间**：各模块的创建日期、执行时间、接入时间等各种日期时间字段改成年月日时分秒，如登录日志的登录时间。
7.建议补充帮助文档(邮箱、双因素认证等不会用)

再次表示感谢

**Comment by dushixiang** [comment]
> 首先特别感谢作者提供这么好这么实用的功能，根据使用情况提出几点建议，希望能改进
> 
> 1.**资产列表**：添加显示IP和点击排序的功能；在操作字段，把高频使用的编辑和复制直接显示出来（或点击资产名称弹出编辑框）；导入时允许导入标签，另外有时无法导入；有Kubernetes协议，但查询条件的下拉列表中没有这个协议，会话审计的查询条件也没有这个协议；增加状态这个字段的查询条件。
> 2.**指令列表**：把高频使用的编辑直接显示出来（或点击指令名称弹出编辑框）；添加telnet的支持，华为、H3C等路由器交换机经常要执行一批命令。
> 3.**在线会话**和**历史会话**：增加显示主机IP，并允许排序。
> 4.**计划任务**：把高频使用的编辑直接显示出来（或点击任务名称弹出编辑框）。
> 5.**系统设置**：远程windows桌面时老是自动重连，建议在安装时，“禁用字形缓存”默认开启。
> 6.**关于日期时间**：各模块的创建日期、执行时间、接入时间等各种日期时间字段改成年月日时分秒，如登录日志的登录时间。
> 7.建议补充帮助文档(邮箱、双因素认证等不会用)
> 
> 再次表示感谢
感谢您提供的建议。
1. 资产列表是有显示IP的，把鼠标悬浮到协议上方即可，原因是列显示的信息太多会导致格式错乱。k8s协议过滤下个版本加上，之前疏忽了。
2. 执行telnet命令尚未开发完成。
3. 同样的把鼠标悬浮到协议上方可以查看到IP。
4. 目前都是按照添加日期排序的，感觉提供自定义顺序排序可能会比较好。
5. 这条可行。
6. 日期也是鼠标悬浮就会显示标准格式。
7. 邮箱功能目前还不完善，只是用于给新用户发送信息。双因素认证就是类似QQ安全中心的东西。

**Comment by dreamskr** [comment]
自己手动解决了
![1](https://user-images.githubusercontent.com/43511466/119147503-30d47980-ba3b-11eb-9391-0bd9a6fe40ab.png)

有需要的，备份/usr/local/next-terminal/web/build目录，再上传此附件上去覆盖即可。
[build.zip](https://github.com/dushixiang/next-terminal/files/6522941/build.zip)

修改过的src\components源码如下
[src.zip](https://github.com/dushixiang/next-terminal/files/6522969/src.zip)
