### ISSUE TITLE
【紧急】k8s怎么配置，我连不上，认证失败

### ISSUE THREAD

**Issue by bingws** [dushixiang/next-terminal#145]
k8s怎么配置，我连不上，认证失败

![image](https://user-images.githubusercontent.com/10806595/119076027-6e79d800-ba24-11eb-825c-6eab79689285.png)

错误提示“远程服务异常”

**Comment by dushixiang** [comment]
> k8s怎么配置，我连不上，认证失败
> 
> ![image](https://user-images.githubusercontent.com/10806595/119076027-6e79d800-ba24-11eb-825c-6eab79689285.png)
> 
> 错误提示“远程服务异常”

忽略证书勾选了之后上面填写的SSL认证信息将会被忽略

**Comment by bingws** [comment]
选了否，还是同样的错误。@dushixiang
