### ISSUE TITLE
批量导入能否增加 标签 一列

### ISSUE THREAD

**Issue by sifanx** [dushixiang/next-terminal#147]
你好，批量导入能否增加 标签 一列，标签功能还是挺方便的，便于后期搜索，现在发现导入模版里没有“标签”这一列，导致导入数据以后，还要再对每条信息进行编辑增加标签，增加很多工作量。

**Comment by dushixiang** [comment]
> 你好，批量导入能否增加 标签 一列，标签功能还是挺方便的，便于后期搜索，现在发现导入模版里没有“标签”这一列，导致导入数据以后，还要再对每条信息进行编辑增加标签，增加很多工作量。

下次版本会增加此功能。

**Comment by sifanx** [comment]
好的，谢谢，那批量导入支持 授权凭证 的导入，有研究出来吗？ 之前是问说不支持的

**Comment by dushixiang** [comment]
> 好的，谢谢，那批量导入支持 授权凭证 的导入，有研究出来吗？ 之前是问说不支持的

暂时不支持这样操作。
