### ISSUE TITLE
能否增加使用代理连接

### ISSUE THREAD

**Issue by result-bit** [dushixiang/next-terminal#148]
安装在国内，对于某些网络质量不是很好的国外服务器。链接过去Web Terminal就会很卡，反之也是。
所以作者可否增加一个使用socks5代理连接ssh的功能？

**Comment by dushixiang** [comment]
> 安装在国内，对于某些网络质量不是很好的国外服务器。链接过去Web Terminal就会很卡，反之也是。
> 所以作者可否增加一个使用socks5代理连接ssh的功能？

抱歉，此项目并非适用于跨区域使用，暂时不会增加此功能。
