### ISSUE TITLE
RDP连接方式下浏览器改变窗口大小会导致重新连接选择用户登录？

### ISSUE THREAD

**Issue by althyman** [dushixiang/next-terminal#149]
环境：WIN10, Chrome91,  局域网RDP连接资产WinServer2012。
操作：连接成功后，改变浏览器窗口大小后，H5重渲染会闪烁，类似于重新创建了一个session去连接到win。 我不确定这是Guacamole的问题还是后端对session处理的问题？
感谢答复！

**Comment by dushixiang** [comment]
> 环境：WIN10, Chrome91, 局域网RDP连接资产WinServer2012。
> 操作：连接成功后，改变浏览器窗口大小后，H5重渲染会闪烁，类似于重新创建了一个session去连接到win。 我不确定这是Guacamole的问题还是后端对session处理的问题？
> 感谢答复！

RDP连接改变窗口大小之后会自动进行重连，但会话还是同一个。

**Comment by althyman** [comment]
> > 环境：WIN10, Chrome91, 局域网RDP连接资产WinServer2012。
> > 操作：连接成功后，改变浏览器窗口大小后，H5重渲染会闪烁，类似于重新创建了一个session去连接到win。 我不确定这是Guacamole的问题还是后端对session处理的问题？
> > 感谢答复！
> 
> RDP连接改变窗口大小之后会自动进行重连，但会话还是同一个。

谢谢~
