### ISSUE TITLE
请问0.4.1升级到0.5.0需要更新guacamole到1.3吗？

### ISSUE THREAD

**Issue by sifanx** [dushixiang/next-terminal#152]
我现在用的是0.4.1的版本，暂时没敢升级到0.5.0，看到更新日志上写“升级guacd版本为1.3.0”，0.4.1用的还是guacd v1.2.0，不知道next升级到0.5.0会不会有问题？需不需要把guacamole从1.2.0升级到1.3.0吗？还是不用升级就可以直接使用的？

**Comment by dushixiang** [comment]
> 我现在用的是0.4.1的版本，暂时没敢升级到0.5.0，看到更新日志上写“升级guacd版本为1.3.0”，0.4.1用的还是guacd v1.2.0，不知道next升级到0.5.0会不会有问题？需不需要把guacamole从1.2.0升级到1.3.0吗？还是不用升级就可以直接使用的？

可以直接使用。
