### ISSUE TITLE
建议增加快速管理方式，例如终端页面可以独立出来，左边加上书签管理器

### ISSUE THREAD

**Issue by blackboar** [dushixiang/next-terminal#154]
建议增加快速管理方式，例如终端页面可以独立出来，左边加上书签管理器

我看到 #128有提到

使用了1个多月了，很轻巧很喜欢，就是分组功能也不是很完善，主机太多了之后管理太不方便了，希望能实现独立出来，然后主机分组放在页面里，要进那个直接就可以高效率的进去了。

**Comment by dushixiang** [comment]
> 建议增加快速管理方式，例如终端页面可以独立出来，左边加上书签管理器
> 
> 
> 
> 我看到 #128有提到
> 
> 
> 
> 使用了1个多月了，很轻巧很喜欢，就是分组功能也不是很完善，主机太多了之后管理太不方便了，希望能实现独立出来，然后主机分组放在页面里，要进那个直接就可以高效率的进去了。

分组功能是使用标签做的，快速连接还在开发中

**Comment by dushixiang** [comment]
不打算做这个功能了
