### ISSUE TITLE
windows10未知错误

### ISSUE THREAD

**Issue by TianmoTTT** [dushixiang/next-terminal#155]
登录win10桌面，现实登录成功，随后提示未知错误。debian10  next 1.3.0   360浏览器。

**Comment by TianmoTTT** [comment]
![Uploading 121676547...]()![Uploading 121676548...]()

**Comment by TianmoTTT** [comment]
![Uploading 121676644...]()

**Comment by TianmoTTT** [comment]
![image](https://user-images.githubusercontent.com/32138819/121677394-5f98b980-cae8-11eb-9722-fb1e2fa81e69.png)

**Comment by TianmoTTT** [comment]
![image](https://user-images.githubusercontent.com/32138819/121677420-68898b00-cae8-11eb-9712-9e294bdff3ec.jpeg)

**Comment by dushixiang** [comment]
> ![image](https://user-images.githubusercontent.com/32138819/121677394-5f98b980-cae8-11eb-9722-fb1e2fa81e69.png)

这个像是安装guacamole/guacd未成功。
