### ISSUE TITLE
明明资产在线，为什么都是显示不在线，而且都连接不上

### ISSUE THREAD

**Issue by nbnb666888** [dushixiang/next-terminal#157]
![image](https://user-images.githubusercontent.com/68323911/122150141-c3780500-ce8f-11eb-8f10-2065426db15f.png)
如图，我这三台机器其实都是在线的，但是都显示不在线，而且点击连接连接不上。奇怪的是，我刚搭建的时候是可以连接的，过了几天就现在这样不行了。

Version:0.4.1

**Comment by nbnb666888** [comment]
docker 重装了下，好了。。。不知道活几天会不会突然又挂掉。。。

**Comment by dushixiang** [comment]
> docker 重装了下，好了。。。不知道活几天会不会突然又挂掉。。。

docker网络问题，进入docker里面排查一下即可，如果实在不了解docker可以用host网络模式，这样宿主机器可以访问到就行。
