### ISSUE TITLE
rdp 提示 远程服务不可用

### ISSUE THREAD

**Issue by heirychen** [dushixiang/next-terminal#159]
远程是 win7，连上后，右击桌面就提示 远程服务不可用，使用客户端可以正常连接操作。

**Comment by dushixiang** [comment]
> 远程是 win7，连上后，右击桌面就提示 远程服务不可用，使用客户端可以正常连接操作。

请参考 https://github.com/dushixiang/next-terminal/blob/master/docs/faq.md
