### ISSUE TITLE
Waiting for server response.........

### ISSUE THREAD

**Issue by kakafred** [dushixiang/next-terminal#161]
![image](https://user-images.githubusercontent.com/82210954/123610671-61c27e00-d833-11eb-8f92-89c8d2f6c61b.png)

RDP connections always show me this 
I don't know how to fix it .Maybe my RDP settings was wrong.

This is my RDP connection Settings:
 
![image](https://user-images.githubusercontent.com/82210954/123611060-c8479c00-d833-11eb-8207-87fc64da112a.png)

But my SSH is working.

**Comment by kakafred** [comment]
I installed Next terminal on my ubuntu OS. Not docker

**Comment by dushixiang** [comment]
> ![image](https://user-images.githubusercontent.com/82210954/123610671-61c27e00-d833-11eb-8f92-89c8d2f6c61b.png)
> 
> RDP connections always show me this
> I don't know how to fix it .Maybe my RDP settings was wrong.
> 
> This is my RDP connection Settings:
> 
> ![image](https://user-images.githubusercontent.com/82210954/123611060-c8479c00-d833-11eb-8207-87fc64da112a.png)
> 
> But my SSH is working.

You can check the log of the guacd service in /var/log/message

**Comment by kakafred** [comment]
找到问题了，是因为我修改了guacd.conf    /etc/guacamole/guacd.conf配置文件里的4822端口导致的。
在设置里修改，请不要在guacd配置文件修改，不会起作用。
改回4822 即可RDP连接。
