### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by ixinshang** [dushixiang/next-terminal#162]
首先，感谢开发这么好用的工具。 住的地方，安顿下来了吗？ 
提几条使用的情况，可否考虑增加以下功能，谢谢
1:增加强制超时关闭会话（设置默认对话时间，无操作就强制关闭会话）
2:在WEB页面，密码不可见（现在可以通过点击那个眼睛按钮查看）
3:登录页面可否增加验证码，防基本爆破
4:是否可以指定某些账户强制开启双因子

**Comment by ixinshang** [comment]
另外更新所有者或者授权人，可以批量更新多个资产的吗

**Comment by dushixiang** [comment]
> 首先，感谢开发这么好用的工具。 住的地方，安顿下来了吗？
> 提几条使用的情况，可否考虑增加以下功能，谢谢
> 1:增加强制超时关闭会话（设置默认对话时间，无操作就强制关闭会话）
> 2:在WEB页面，密码不可见（现在可以通过点击那个眼睛按钮查看）
> 3:登录页面可否增加验证码，防基本爆破
> 4:是否可以指定某些账户强制开启双因子

1. 可以从机器上配置超时时间
2. 此功能目前还在设计
3. 开启双因子认证之后可防爆破
4. 暂时不会做
5. 可以从用户/用户组视角操作
