### ISSUE TITLE
请问Remote App（RDPAPP）如何配置？

### ISSUE THREAD

**Issue by updsky** [dushixiang/next-terminal#163]
看到新版本中对RDP协议提供了Remote App的支持，但是怎么配置都失败，请问应该怎么配置？

**Comment by dushixiang** [comment]
首先你的目标机器需要支持remote app才行，据我所知只有win server支持。
其他版本的windows可以试下 https://github.com/stascorp/rdpwrap

**Comment by dushixiang** [comment]
> 看到新版本中对RDP协议提供了Remote App的支持，但是怎么配置都失败，请问应该怎么配置？


首先你的目标机器需要支持remote app才行，据我所知只有win server支持。
其他版本的windows可以试下 https://github.com/stascorp/rdpwrap
