### ISSUE TITLE
关于示例网站的程序版本V1.0.0-Beta

### ISSUE THREAD

**Issue by walkmiao** [dushixiang/next-terminal#164]
目前master分支tag最高为v0.5.0的，我测试了一下指令动态执行不支持telnet和rdp等协议，只有ssh支持。
但是看示例网站中是支持这些功能的，我看了一下版本是beta版。请问作者能否把这一版放出来呢，因为目前的使用场景不允许使用ssh只可以用telnet等，万分感谢！

**Comment by dushixiang** [comment]
> 目前master分支tag最高为v0.5.0的，我测试了一下指令动态执行不支持telnet和rdp等协议，只有ssh支持。
> 但是看示例网站中是支持这些功能的，我看了一下版本是beta版。请问作者能否把这一版放出来呢，因为目前的使用场景不允许使用ssh只可以用telnet等，万分感谢！

现在测试的版本也只支持执行SSH的指令。

**Comment by walkmiao** [comment]
好的 非常感谢！

**Comment by dushixiang** [comment]
v1.0.0 已发布。
