### ISSUE TITLE
重新根据Dockerfile编译的问题

### ISSUE THREAD

**Issue by ZJahon** [dushixiang/next-terminal#167]
在运行 docker build -t test /root/next-terminal-master后，程序一直执行，直到执行Dockerfile中的以下代码时：
COPY --from=builder /app/web/build ./web/build
报错：
COPY failed: stat /var/lib/docker/overlay2/d92e60b9c2050c020b7323787262f1b037ae4e4e7fc03f5689cd6df70ee04272/merged/app/web/build: no such file or directory
请问是什么原因导致的？如何解决呢？

**Comment by xayle** [comment]
git 代码中的 web 没有编译, 需要编译或者下载编译好的.

**Comment by dushixiang** [comment]
> 在运行 docker build -t test /root/next-terminal-master后，程序一直执行，直到执行Dockerfile中的以下代码时：
> COPY --from=builder /app/web/build ./web/build
> 报错：
> COPY failed: stat /var/lib/docker/overlay2/d92e60b9c2050c020b7323787262f1b037ae4e4e7fc03f5689cd6df70ee04272/merged/app/web/build: no such file or directory
> 请问是什么原因导致的？如何解决呢？

前端项目使用docker编译总是会内存不足，所以是在宿主机器上编译的，运行dockerfile需要先编译前端。

**Comment by ZJahon** [comment]
请问前端怎么编译

**Comment by xayle** [comment]
使用 npm 或者 yarn, 建议 2核4G以上.
