### ISSUE TITLE
Centos8 mini安装中文版，ssh连上中文乱码

### ISSUE THREAD

**Issue by sifanx** [dushixiang/next-terminal#168]
你好，我在虚拟机上安装CentOS8.4 mini，选的中文简体安装，在next-terminal连入后，发现中文会乱码，这个有什么办法解决吗？
![zwlm](https://user-images.githubusercontent.com/42561369/125925817-579bb366-4491-48b9-83df-4ae266124f12.jpg)

**Comment by sifanx** [comment]
用xshell连接centos，中文显示是正常的
![zwzc](https://user-images.githubusercontent.com/42561369/125925992-c62dde63-ccdd-45a3-98d7-ed2999763c00.jpg)

**Comment by qwz160** [comment]
centos7上docker安装，也是出现中文乱码，喜欢处理。。

**Comment by dushixiang** [comment]
请安装中文字体，教程已更新。
https://next-terminal.typesafe.cn/document/#%E5%AE%89%E8%A3%85%E5%AD%97%E4%BD%93-ssh%E4%BD%BF%E7%94%A8
