### ISSUE TITLE
请问 0.5 无法直接升到 1.0 吗？

### ISSUE THREAD

**Issue by sifanx** [dushixiang/next-terminal#171]
我像往常一下替换文件升级，重启以后，发现网页打不开，服务器有报错，文件还原回0.5又好了。这个要怎么升级？

![0 5-1 0](https://user-images.githubusercontent.com/42561369/129993059-b61ecfd2-3b61-400e-9a96-c1f03d5f371b.jpg)

**Comment by dushixiang** [comment]
> 我像往常一下替换文件升级，重启以后，发现网页打不开，服务器有报错，文件还原回0.5又好了。这个要怎么升级？
> 
> ![0 5-1 0](https://user-images.githubusercontent.com/42561369/129993059-b61ecfd2-3b61-400e-9a96-c1f03d5f371b.jpg)

发布了 v1.0.1 版本以修复此问题。

**Comment by sifanx** [comment]
替换v1.0.1的文件可以了，谢谢~
