### ISSUE TITLE
ssh: no key found

### ISSUE THREAD

**Issue by aihui1983** [dushixiang/next-terminal#172]
SSH配置密钥连接方式，使用原生方式和guacd方式均无法连接，服务器使用客户端工具可以正常连接，原生方式错误信息为：

Trying to connect to the server ...
ssh: no key found 
Failed to connect to server.
Connection is closed.

**Comment by dushixiang** [comment]
PuTTY 生成的密钥无法直接使用，需要导出后再使用。
