### ISSUE TITLE
0.5升级到1.0后无法链接原来的SSH和RDP

### ISSUE THREAD

**Issue by dislazy** [dushixiang/next-terminal#175]
- 使用mysql数据库
报错内容：
- SSH: Error 1406: Data too long for column 'private_key' at row 1
- RDP: 创建隧道失败，请检查Guacd服务是否正常。

**Comment by dushixiang** [comment]
> * 使用mysql数据库
>   报错内容：
> * SSH: Error 1406: Data too long for column 'private_key' at row 1
> * RDP: 创建隧道失败，请检查Guacd服务是否正常。

1.0.0 版本的容器将guacd服务进行了拆分，需要使用新的安装方式，请参考 https://next-terminal.typesafe.cn/document/#%E4%BD%BF%E7%94%A8-mysql-%E5%AD%98%E5%82%A8%E6%95%B0%E6%8D%AE

另外私钥长度不够的问题已经进行了修复，请重新拉取镜像（版本还是1.0.0）。

**Comment by dislazy** [comment]
> > * 使用mysql数据库
> >   报错内容：
> > * SSH: Error 1406: Data too long for column 'private_key' at row 1
> > * RDP: 创建隧道失败，请检查Guacd服务是否正常。
> 
> 1.0.0 版本的容器将guacd服务进行了拆分，需要使用新的安装方式，请参考 https://next-terminal.typesafe.cn/document/#%E4%BD%BF%E7%94%A8-mysql-%E5%AD%98%E5%82%A8%E6%95%B0%E6%8D%AE
> 
> 另外私钥长度不够的问题已经进行了修复，请重新拉取镜像（版本还是1.0.0）。

好的  非常感谢

**Comment by dislazy** [comment]
当前数据库模式为：mysql
⇨ http server started on [::]:8088
[root@155 next-terminal]# docker logs --tail=10 -f nextterminal_next-terminal_1

 _______                   __    ___________                  .__              .__
 \      \   ____ ___  ____/  |_  \__    ___/__________  _____ |__| ____ _____  |  |
 /   |   \_/ __ \\  \/  /\   __\   |    |_/ __ \_  __ \/     \|  |/    \\__  \ |  |
/    |    \  ___/ >    <  |  |     |    |\  ___/|  | \/  Y Y  \  |   |  \/ __ \|  |__
\____|__  /\___  >__/\_ \ |__|     |____| \___  >__|  |__|_|  /__|___|  (____  /____/
        \/     \/      \/                     \/            \/        \/     \/      v1.0.0

当前数据库模式为：mysql
⇨ http server started on [::]:8088
{"time":"2021-08-29T11:08:15.91997393+08:00","level":"-","prefix":"echo","file":"recover.go","line":"92","message":"[PANIC RECOVER] crypto/cipher: input not full blocks goroutine 44 [running]:\ngithub.com/labstack/echo/v4/middleware.RecoverWithConfig.func1.1.1(0xcfcd78, 0x1000, 0x0, 0xdbbd00, 0xc0003e5a40)\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.1.17/middleware/recover.go:77 +0x105\npanic(0xbdad20, 0xd94fb0)\n\t/usr/local/go/src/runtime/panic.go:965 +0x1b9\ncrypto/cipher.(*cbcDecrypter).CryptBlocks(0xc0003ec5a0, 0xc000450180, 0x177, 0x177, 0xc000450000, 0x177, 0x177)\n\t/usr/local/go/src/crypto/cipher/cbc.go:119 +0x4e9\nnext-terminal/server/utils.AesDecryptCBC(0xc000450000, 0x177, 0x177, 0xc0000dbec0, 0x20, 0x20, 0x0, 0x0, 0x0, 0x0, ...)\n\t/app/server/utils/utils.go:296 +0x14b\nnext-terminal/server/repository.SessionRepository.Decrypt(0xc0001dfad0, 0xc00026ae00, 0xc00026ae00, 0x0)\n\t/app/server/repository/session.go:124 +0x1af\nnext-terminal/server/repository.SessionRepository.FindByIdAndDecrypt(0xc0001dfad0, 0xc00000a616, 0x24, 0x3, 0xc000022768, 0xc0002c0b00, 0x0, 0x0, 0x0, 0x0, ...)\n\t/app/server/repository/session.go:102 +0x165\nnext-terminal/server/api.TunEndpoint(0xdbbd00, 0xc0003e5a40, 0x0, 0x0)\n\t/app/server/api/tunnel.go:76 +0x17a5\ngithub.com/labstack/echo/v4.(*Echo).add.func1(0xdbbd00, 0xc0003e5a40, 0xc00000a600, 0x3)\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.1.17/echo.go:522 +0x62\nnext-terminal/server/api.License.func1(0xdbbd00, 0xc0003e5a40, 0x9d, 0xc588e0)\n\t/app/server/api/middleware.go:166 +0x1dc\nnext-terminal/server/api.Auth.func1(0xdbbd00, 0xc0003e5a40, 0xc00004d850, 0x7ca0e5)\n\t/app/server/api/middleware.go:122 +0x4e9\nnext-terminal/server/api.TcpWall.func1(0xdbbd00, 0xc0003e5a40, 0x203001, 0x7f755850ff60)\n\t/app/server/api/middleware.go:37 +0x6c5\nnext-terminal/server/api.ErrorHandler.func1(0xdbbd00, 0xc0003e5a40, 0xcdb729, 0x1b)\n\t/app/server/api/middleware.go:19 +0x51\ngithub.com/labstack/echo/v4/middleware.CORSWithConfig.func1.1(0xdbbd00, 0xc0003e5a40, 0xc49600, 0x1)\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.1.17/middleware/cors.go:121 +0x483\ngithub.com/labstack/echo/v4/middleware.RecoverWithConfig.func1.1(0xdbbd00, 0xc0003e5a40, 0x0, 0x0)\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.1.17/middleware/recover.go:98 +0x142\ngithub.com/labstack/echo/v4.(*Echo).ServeHTTP(0xc00000cf00, 0xdafeb0, 0xc00015e1c0, 0xc0002d3200)\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.1.17/echo.go:633 +0x2bc\nnet/http.serverHandler.ServeHTTP(0xc0002a00e0, 0xdafeb0, 0xc00015e1c0, 0xc0002d3200)\n\t/usr/local/go/src/net/http/server.go:2867 +0xa3\nnet/http.(*conn).serve(0xc0003e4780, 0xdb15c0, 0xc000066680)\n\t/usr/local/go/src/net/http/server.go:1932 +0x8cd\ncreated by net/http.(*Server).Serve\n\t/usr/local/go/src/net/http/server.go:2993 +0x39b\n\ngoroutine 1 [IO wait]:\ninternal/poll.runtime_pollWait(0x7f753183ee38, 0x72, 0x0)\n\t/usr/local/go/src/runtime/netpoll.go:222 +0x55\ninternal/poll.(*pollDesc).wait(0xc00007b518, 0x72, 0x0, 0x0, 0xcce852)\n\t/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45\ninternal/poll.(*pollDesc).waitRead(...)\n\t/usr/local/go/src/internal/poll/fd_poll_runtime.go:92\ninternal/poll.(*FD).Accept(0xc00007b500, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/usr/local/go/src/internal/poll/fd_unix.go:401 +0x212\nnet.(*netFD).accept(0xc00007b500, 0x0, 0xb4, 0x203000)\n\t/usr/local/go/src/net/fd_unix.go:172 +0x45\nnet.(*TCPListener).accept(0xc0002c6bd0, 0x29e8d60800, 0x0, 0x0)\n\t/usr/local/go/src/net/tcpsock_posix.go:139 +0x32\nnet.(*TCPListener).AcceptTCP(0xc0002c6bd0, 0x3fcb27decef75d92, 0x0, 0x0)\n\t/usr/local/go/src/net/tcpsock.go:248 +0x65\ngithub.com/labstack/echo/v4.tcpKeepAliveListener.Accept(0xc0002c6bd0, 0xc000113c08, 0x4d4266, 0x612afa1f, 0x442b8e)\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.1.17/echo.go:875 +0x2f\nnet/http.(*Server).Serve(0xc0002a00e0, 0xdaf1c0, 0xc000011688, 0x0, 0x0)\n\t/usr/local/go/src/net/http/server.go:2961 +0x285\ngithub.com/labstack/echo/v4.(*Echo).StartServer(0xc00000cf00, 0xc0002a00e0, 0x20, 0xc0000dbec0)\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.1.17/echo.go:724 +0x385\ngithub.com/labstack/echo/v4.(*Echo).Start(...)\n\t/go/pkg/mod/github.com/labstack/echo/v4@v4.1.17/echo.go:644\nmain.Run(0xc000082058, 0xaa8bf0)\n\t/app/main.go:76 +0x44d\nmain.main()\n\t/app/main.go:30 +0x25\n\ngoroutine 19\n"}
echo: http: response.WriteHeader on hijacked connection from github.com/labstack/echo/v4.(*Response).WriteHeader (response.go:63)
echo: http: response.Write on hijacked connection from github.com/labstack/echo/v4.(*Response).Write (response.go:75)
{"time":"2021-08-29T11:08:15.920148651+08:00","level":"ERROR","prefix":"echo","file":"echo.go","line":"379","message":"http: connection has been hijacked"}

**Comment by dislazy** [comment]
@dushixiang   升级到新版本后 ，RDP连接服务器OK，但是无法连接到SSH

**Comment by dushixiang** [comment]
> @dushixiang 升级到新版本后 ，RDP连接服务器OK，但是无法连接到SSH

发布了 v1.0.1 版本来修复这个问题。

**Comment by dislazy** [comment]
> > @dushixiang 升级到新版本后 ，RDP连接服务器OK，但是无法连接到SSH
> 
> 发布了 v1.0.1 版本来修复这个问题。

响应速度好快，感谢感谢
