### ISSUE TITLE
资产状态检测不正确

### ISSUE THREAD

**Issue by xiaomingtt** [dushixiang/next-terminal#177]
Centos7原生安装，在服务器上ping终端都能通。但系统里面检测状态都是不可用。

**Comment by dushixiang** [comment]
> Centos7原生安装，在服务器上ping终端都能通。但系统里面检测状态都是不可用。

使用的是tcp检测的，你可以用telnet 访问目标端口进行测试，默认超时时间是2秒。

**Comment by xiaomingtt** [comment]
> > Centos7原生安装，在服务器上ping终端可以通。但系统里面检测状态都是不可用的。
> 
> 使用的是tcp检测的，你可以用telnet远程端口进行测试，默认访问时间是2秒。

测试Telnet没问题，基本瞬间就能连接上，但状态一直不可用。

**Comment by dushixiang** [comment]
> > > Centos7原生安装，在服务器上ping终端可以通。但系统里面检测状态都是不可用的。
> 
> > 
> 
> > 使用的是tcp检测的，你可以用telnet远程端口进行测试，默认访问时间是2秒。
> 
> 
> 
> 测试Telnet没问题，基本瞬间就能连接上，但状态一直不可用。

发布了 v1.0.4 修复了此问题
