### ISSUE TITLE
以后是否考虑增加二级目录访问？

### ISSUE THREAD

**Issue by duanYYu** [dushixiang/next-terminal#18]
现在使用nginx localtion /test/ { ………………} 反向代理   点击页面 报错404 。小白猜测 页面上写的是绝对路径，是否可以修改为相对路径？
例如访问地址为：http://172.15.35.23:8081/next-terminal/ 
nginx配置为
![image](https://user-images.githubusercontent.com/35124358/103757008-1e890e80-504b-11eb-975a-f050e5d65e22.png)
前端报错为：
![image](https://user-images.githubusercontent.com/35124358/103757046-2a74d080-504b-11eb-86df-cb7adbc5ae9a.png)

**Comment by dushixiang** [comment]
暂时无法增加。

**Comment by AndroidOL** [comment]
同样问题，你把加一段 location /login，/overview，/logout 之后还是可以用的，需要把 cookie 转过来
