### ISSUE TITLE
RDP下怎么传文件？

### ISSUE THREAD

**Issue by IzualYang** [dushixiang/next-terminal#181]
上传文件界面可以上传到NextTerminal服务器端的文件夹下，但被控端怎么访问这个文件夹或者直接和控制端传文件？

**Comment by dushixiang** [comment]
> 上传文件界面可以上传到NextTerminal服务器端的文件夹下，但被控端怎么访问这个文件夹或者直接和控制端传文件？
> 
> 

在Windows文件管理器与C盘同级目录的地方，前提是开启了文件挂载盘。

**Comment by RookieTerry** [comment]
没有找到“设备映射”
