### ISSUE TITLE
前端未处理状态:  8.required,8.password;

### ISSUE THREAD

**Issue by orestonce** [dushixiang/next-terminal#186]
* vnc服务器，需要密码才能链接
* 添加一个资产，类型为vnc，在配置部分不填写用户名密码，保存
* 点击资产的“接入”按钮，在新开的tab页面里的websocket的第一个包返回的是 "8.required,8.password;" ， 页面一直loading "正在等待服务器响应..."

**Comment by dushixiang** [comment]
> * vnc服务器，需要密码才能链接
> 
> * 添加一个资产，类型为vnc，在配置部分不填写用户名密码，保存
> 
> * 点击资产的“接入”按钮，在新开的tab页面里的websocket的第一个包返回的是 "8.required,8.password;" ， 页面一直loading "正在等待服务器响应..."

有密码认证的需要填写密码之后才能使用
