### ISSUE TITLE
关于guacamole 连接window文件上传

### ISSUE THREAD

**Issue by qianyewu** [dushixiang/next-terminal#188]
您好，想请教一下，这个右上角这些按钮是怎么实现的。我想在django项目中加入**rdp/vnc**连接远程**window**，并**上传下载**文件，我配置了guacd可以连接window，现在想实现文件上传下载，但是无从下手，有幸看到大佬的项目，想请问您这个是怎么实现的？用的js插件还是什么方法？（emmmm因为看不懂go的项目，冒昧了）
![图片](https://user-images.githubusercontent.com/43900412/139632189-2f1ebb20-ff2b-42bf-bb9c-871ee6f19012.png)

**Comment by dushixiang** [comment]
> 您好，想请教一下，这个右上角这些按钮是怎么实现的。我想在django项目中加入**rdp/vnc**连接远程**window**，并**上传下载**文件，我配置了guacd可以连接window，现在想实现文件上传下载，但是无从下手，有幸看到大佬的项目，想请问您这个是怎么实现的？用的js插件还是什么方法？（emmmm因为看不懂go的项目，冒昧了）
> 
> ![图片](https://user-images.githubusercontent.com/43900412/139632189-2f1ebb20-ff2b-42bf-bb9c-871ee6f19012.png)
> 
> 

windows 实现方式是上传到一个指定目录，guacd挂载盘指向这里。
ssh 实现方式是创建一个sftp客户端操作目标资产。

**Comment by qianyewu** [comment]
好的  谢谢您的回答，
我试了一下，使用 
`        enable-drive = true
        drive-path = '/path'
        create-drive-path = true`
可以挂载了，window可以访问。

另外（为啥我的web端win界面还是没有那几个小图标呀  emmmmmmm）

**Comment by dushixiang** [comment]
> 好的 谢谢您的回答， 我试了一下，使用 ` enable-drive = true drive-path = '/path' create-drive-path = true` 可以挂载了，window可以访问。
> 
> 另外（为啥我的web端win界面还是没有那几个小图标呀 emmmmmmm）

前端需要自己实现

**Comment by qianyewu** [comment]
> 
> 
> > 好的 谢谢您的回答， 我试了一下，使用 ` enable-drive = true drive-path = '/path' create-drive-path = true` 可以挂载了，window可以访问。
> > 另外（为啥我的web端win界面还是没有那几个小图标呀 emmmmmmm）
> 
> 前端需要自己实现

好的，我还以为官方有直接的参数设置的，总之 非常感谢您!
