### ISSUE TITLE
ssh连接 下载文件，文件名不是原文件名

### ISSUE THREAD

**Issue by duanYYu** [dushixiang/next-terminal#19]
源文件名为：docker.tar.gz  下载后文件名为：_usr_local_src_docker.tar.gz 文件截图：
![image](https://user-images.githubusercontent.com/35124358/103757406-b1c24400-504b-11eb-9e85-2232a0df8e75.png)

**Comment by dushixiang** [comment]
已确认，下个版本修复。

**Comment by dushixiang** [comment]
v0.0.6版本修复了这个问题。
