### ISSUE TITLE
关于admin账号不小心修改成普通用户后无法登陆

### ISSUE THREAD

**Issue by ggfvictor** [dushixiang/next-terminal#196]
作者您好，问题如题，是否可以把admin写死成管理员或者至少有一个用户需要是管理员。

**Comment by dushixiang** [comment]
> 作者您好，问题如题，是否可以把admin写死成管理员或者至少有一个用户需要是管理员。

感谢反馈，下个版本会加上强制检验。

**Comment by dushixiang** [comment]
> > 作者您好，问题如题，是否可以把admin写死成管理员或者至少有一个用户需要是管理员。
> 
> 感谢反馈，下个版本会加上强制检验。

已在 v1.2.1 版本中增加
