### ISSUE TITLE
希望能增加多屏切换的功能

### ISSUE THREAD

**Issue by panda62** [dushixiang/next-terminal#197]
希望能增加多屏切换的功能，现在远程多屏的电脑无法显示多屏内容；
希望有设置分辨率，单个屏幕显示不完整，需要在链接前对页面先进行缩放；
感谢开发出这个工具，谢谢！

**Comment by panda62** [comment]
现在用的vnc远程桌面

**Comment by dushixiang** [comment]
> 希望能增加多屏切换的功能，现在远程多屏的电脑无法显示多屏内容；
> 
> 希望有设置分辨率，单个屏幕显示不完整，需要在链接前对页面先进行缩放；
> 
> 感谢开发出这个工具，谢谢！

抱歉，由于技术限制，无法支持这个功能。
