### ISSUE TITLE
无法使用授权凭证（密钥）登录

### ISSUE THREAD

**Issue by lostrain** [dushixiang/next-terminal#199]
next-terminal 版本：1.2.0
MySQL版本：8.0.27
使用方式：添加了一个授权凭证，账户类型是密钥，并将我本地的私钥粘贴了上去，然后资产配置中选该授权凭证登录；或者资产信息中直接配置使用密钥登录；
问题：接入的界面报 提示 Error 1406: Data too long for column 'private_key' at row 1
尝试：查看MySQL中的assets表和credentials表，发现private_key字段已经是text类型，尝试修改为longtext类型仍未解决问题；

**Comment by dushixiang** [comment]
> next-terminal 版本：1.2.0 MySQL版本：8.0.27 使用方式：添加了一个授权凭证，账户类型是密钥，并将我本地的私钥粘贴了上去，然后资产配置中选该授权凭证登录；或者资产信息中直接配置使用密钥登录； 问题：接入的界面报 提示 Error 1406: Data too long for column 'private_key' at row 1 尝试：查看MySQL中的assets表和credentials表，发现private_key字段已经是text类型，尝试修改为longtext类型仍未解决问题；

应该是 `sessions` 表的 `private_key`，之前有个版本字段类型设置错误了。

**Comment by lostrain** [comment]
修改了`sessions`表的 `private_key`确实解决了上面的问题；但我又遇到一个问题，我生成私钥时并没有设置密码，然而进入到页面会提示 `Key passphrase: `，是一个等待输入密码的状态。不知道这个是我的使用问题还是一个缺陷

**Comment by dushixiang** [comment]
> 修改了`sessions`表的 `private_key`确实解决了上面的问题；但我又遇到一个问题，我生成私钥时并没有设置密码，然而进入到页面会提示 `Key passphrase: `，是一个等待输入密码的状态。不知道这个是我的使用问题还是一个缺陷

使用原生的ssh吧，guacd部分密钥不支持。

**Comment by lostrain** [comment]
OK，感谢解答，切换到原生的ssh确实可以连接了
