### ISSUE TITLE
更改密码不能用

### ISSUE THREAD

**Issue by jackwen999** [dushixiang/next-terminal#2]
更改密码不能用

**Comment by jackwen999** [comment]
后台缺一个登出按钮

**Comment by dushixiang** [comment]
> 后台缺一个登出按钮

这个正在写了。

> 更改密码不能用

这个已经确认，下个版本会修复。

**Comment by jackwen999** [comment]
第一次在github评论，大佬回复了！！^^ 
PS: 面板很好用，建议加上开启ssl

**Comment by dushixiang** [comment]
0.0.2版本修复了这个问题，登出的功能也已经添加，感谢表哥的细心。
