### ISSUE TITLE
中文无法正常显示的问题

### ISSUE THREAD

**Issue by tcyw** [dushixiang/next-terminal#200]
![image](https://user-images.githubusercontent.com/51114421/141717184-a65163f3-c2b4-4545-82c7-19aa59eb7f73.png)
页面上有中文的会乱码

**Comment by dushixiang** [comment]
> ![image](https://user-images.githubusercontent.com/51114421/141717184-a65163f3-c2b4-4545-82c7-19aa59eb7f73.png) 页面上有中文的会乱码

需要安装中文字体 https://next-terminal.typesafe.cn/install/native-install.html#%E5%AE%89%E8%A3%85%E5%AD%97%E4%BD%93-ssh%E4%BD%BF%E7%94%A8

**Comment by Ryanznoco** [comment]
安装了字体仍然乱码
