### ISSUE TITLE
能否增加 aarch64 的支持,我用树莓派4B 装不上

### ISSUE THREAD

**Issue by nmb0725** [dushixiang/next-terminal#201]
安装时提示 docker: no matching manifest for linux/arm/v7 in the manifest list entries.

**Comment by dushixiang** [comment]
> 安装时提示 docker: no matching manifest for linux/arm/v7 in the manifest list entries.

docker的已经支持 arm64 的了

**Comment by nmb0725** [comment]
> > 安装时提示 docker: no matching manifest for linux/arm/v7 in the manifest list entries.
> 
> docker的已经支持 arm64 的了

是的, 我看到了..  可树莓派的 需要支持  linux/arm/v7 . 我试了ARM64的装不上... 所以才来找您求助

**Comment by dushixiang** [comment]
> > > 安装时提示 docker: no matching manifest for linux/arm/v7 in the manifest list entries.
> > 
> > 
> > docker的已经支持 arm64 的了
> 
> 是的, 我看到了.. 可树莓派的 需要支持 linux/arm/v7 . 我试了ARM64的装不上... 所以才来找您求助

我在 GitHub Action 增加  linux/arm/v7 平台试下

**Comment by nmb0725** [comment]
> > > > 安装时提示 docker: no matching manifest for linux/arm/v7 in the manifest list entries.
> > > 
> > > 
> > > docker的已经支持 arm64 的了
> > 
> > 
> > 是的, 我看到了.. 可树莓派的 需要支持 linux/arm/v7 . 我试了ARM64的装不上... 所以才来找您求助
> 
> 我在 GitHub Action 增加 linux/arm/v7 平台试下

感恩~~~~~~~~~~

**Comment by nmb0725** [comment]
看到更新好了,  已经安装完成, 用上了.  无限感恩
