### ISSUE TITLE
用户管理中用户的在线状态一直显示为在线

### ISSUE THREAD

**Issue by wdwnet** [dushixiang/next-terminal#202]
用户管理中用户的在线状态一直显示为在线 @v1.1.0 @v1.2.0 @v1.2.1

**Comment by dushixiang** [comment]
> 用户管理中用户的在线状态一直显示为在线 @v1.1.0 @v1.2.0 @v1.2.1

需要将全部登陆过的token 退出登陆才会更改状态，或者等待过了token 的有效期。
