### ISSUE TITLE
[bug] 备份与恢复 在使用时有个BUG

### ISSUE THREAD

**Issue by nmb0725** [dushixiang/next-terminal#205]
{"accessGatewayId":"-","accountType":"custom","active":true,"created":"2021-11-20T01:16:47.051+08:00"

备份文件在记录网关这里使用的日期 是 UTC的. 但是在恢复时会提示

parsing time "2021-11-20T01:16:47.051+08:00" as "2006-01-02 15:04:05": cannot parse "T01:16:47.051+08:00" as " "

需要自己手工改成 2021-11-20 01:16:47.05

另外有二个小建议:

1. 在安装帮助中只有关于 docker-compose 的安装方法, 希望可以加入 

docker run -d --name guacd --restart=unless-stopped -v /root/net-terminal/data:/usr/local/next-terminal/data -p 4822:4822 dushixiang/guacd:1.3.0

docker run -d -p 8088:8088 --name next-terminal -e DB="sqlite" -e GUACD_HOSTNAME="guacd" -e GUACD_PORT="4822" -v /etc/localtime:/etc/localtime -v /root/net-terminal/data:/usr/local/next-terminal/data --restart=unless-stopped dushixiang/next-terminal:latest

docker run -d -p 8088:8088 --name next-terminal -e DB="mysql" -e MYSQL_HOSTNAME="mysql" -e MYSQL_PORT="3306" -e MYSQL_USERNAME="next-terminal" -e MYSQL_PASSWORD="next-terminal" -e MYSQL_DATABASE="next-terminal" -e GUACD_HOSTNAME="guacd" -e GUACD_PORT="4822" -v /etc/localtime:/etc/localtime -v /root/net-terminal/data:/usr/local/next-terminal/data --restart=unless-stopped dushixiang/next-terminal:latest

2.  在 rdp 的实际使用中,  只打开 "禁用字形缓存" ,有时候还是连不上, 要把"禁用位图缓存" 也打开 ,才能正常连接成功.  希望也可以加入常见问题中.

**Comment by dushixiang** [comment]
> 

感谢发现的bug和提供的建议，稍后我就进行修复和更新。
