### ISSUE TITLE
建议WINDOWS RDP支持网关

### ISSUE THREAD

**Issue by yayaw** [dushixiang/next-terminal#207]
如题：
这个功能，是否能支持呢

**Comment by dushixiang** [comment]
> 如题： 这个功能，是否能支持呢

如果你指的是 RD 网关是可以支持的。

**Comment by yayaw** [comment]
> > 如题： 这个功能，是否能支持呢
> 
> 如果你指的是 RD 网关是可以支持的。

我说的是通过SSH网关，访问后面的WINDOWS服务器，是否可以支持呢，这个功能很实用的哈

**Comment by dushixiang** [comment]
> > > 如题： 这个功能，是否能支持呢
> > 
> > 
> > 如果你指的是 RD 网关是可以支持的。
> 
> 我说的是通过SSH网关，访问后面的WINDOWS服务器，是否可以支持呢，这个功能很实用的哈

这个功能目前已经是支持的。

**Comment by yayaw** [comment]
> > > > 如题： 这个功能，是否能支持呢
> > > 
> > > 
> > > 如果你指的是 RD 网关是可以支持的。
> > 
> > 
> > 我说的是通过SSH网关，访问后面的WINDOWS服务器，是否可以支持呢，这个功能很实用的哈
> 
> 这个功能目前已经是支持的。

哪我在试试吧，我怎么试都不行，但我用JUMPSERVER是可以的。不知道你测试过吗，用哪个测试功能，网关也是通的

**Comment by dushixiang** [comment]
> > > > > 如题： 这个功能，是否能支持呢
> > > > 
> > > > 
> > > > 如果你指的是 RD 网关是可以支持的。
> > > 
> > > 
> > > 我说的是通过SSH网关，访问后面的WINDOWS服务器，是否可以支持呢，这个功能很实用的哈
> > 
> > 
> > 这个功能目前已经是支持的。
> 
> 哪我在试试吧，我怎么试都不行，但我用JUMPSERVER是可以的。不知道你测试过吗，用哪个测试功能，网关也是通的

请参考使用文档 https://next-terminal.typesafe.cn/usage/resource.html#%E6%8E%A5%E5%85%A5%E7%BD%91%E5%85%B3
