### ISSUE TITLE
功能建议：guacd和next-terminal做成一个容器

### ISSUE THREAD

**Issue by fcwys** [dushixiang/next-terminal#211]
guacd和next-terminal做成一个容器，目前使用中，发现guacd容器使用的系统账户是guacd，而测试了next-terminal也可以以普通用户运行，所以建议直接两个服务使用同一个普通用户去运行，容器映射目录权限设置也方便些，便于管理。

**Comment by dushixiang** [comment]
> guacd和next-terminal做成一个容器，目前使用中，发现guacd容器使用的系统账户是guacd，而测试了next-terminal也可以以普通用户运行，所以建议直接两个服务使用同一个普通用户去运行，容器映射目录权限设置也方便些，便于管理。

目录权限的问题，今天会进行修复或增加说明文档

**Comment by fcwys** [comment]
好的，感谢！

**Comment by dushixiang** [comment]
已修改 guacd 容器的默认用户为 root
