### ISSUE TITLE
Responsible disclosure policy

### ISSUE THREAD

**Issue by JamieSlome** [dushixiang/next-terminal#214]
Hey there!

I belong to an open source security research community, and a member (@dwisiswant0) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by dushixiang** [comment]
> 



> Hey there!
> 
> I belong to an open source security research community, and a member (@dwisiswant0) has found an issue, but doesn’t know the best way to disclose it.
> 
> If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.
> 
> Thank you for your consideration, and I look forward to hearing from you!
> 
> (cc @huntr-helper)

Thank you very much for your reminder, I will add SECURITY.md with my email address later. My email is helloworld1024@foxmail.com, we can communicate first to ensure that this problem is repaired as soon as possible.
