### ISSUE TITLE
能增加鼠标右键粘贴吗

### ISSUE THREAD

**Issue by avrileader** [dushixiang/next-terminal#215]
感觉会方便很多，还有就是使用guacd连接SSH不能回放嘛，原生我试了可以，一点建议和疑问，谢谢！

**Comment by dushixiang** [comment]
> 感觉会方便很多，还有就是使用guacd连接SSH不能回放嘛，原生我试了可以，一点建议和疑问，谢谢！

开启https后可以guacd可以与系统剪贴板进行同步，右键即可粘贴。
回放的问题可以看下guacd的日志，可能是没有对应目录的写权限。

**Comment by avrileader** [comment]
好的，谢谢！

**Comment by avrileader** [comment]
我用群晖开启的反代，报了一个错误：2022-01-03 10:18:20 ERROR [logrus.(*Entry).Logf:314]升级为WebSocket协议失败：websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header
echo: http: superfluous response.WriteHeader call from github.com/labstack/echo/v4.(*Response).WriteHeader (response.go:63)
必须要用nginx吗

**Comment by dushixiang** [comment]
> 我用群晖开启的反代，报了一个错误：2022-01-03 10:18:20 ERROR [logrus.(*Entry).Logf:314]升级为WebSocket协议失败：websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header echo: http: superfluous response.WriteHeader call from github.com/labstack/echo/v4.(*Response).WriteHeader (response.go:63) 必须要用nginx吗

群晖也是支持的，你参考nginx 的设置，把 Upgrade 和 Connection 这两个header加上去就行。

**Comment by avrileader** [comment]
设置成功了，感谢

**Comment by ukiyoec** [comment]
> 

大佬你好请问是怎么添加啊具体的代码能发下吗

**Comment by ZhiboWong** [comment]
> > 感觉会方便很多，还有就是使用guacd连接SSH不能回放嘛，原生我试了可以，一点建议和疑问，谢谢！
> 
> 开启https后可以guacd可以与系统剪贴板进行同步，右键即可粘贴。 回放的问题可以看下guacd的日志，可能是没有对应目录的写权限。

如何开启https呢？
