### ISSUE TITLE
那个接入网关怎么用？

### ISSUE THREAD

**Issue by allcdn** [dushixiang/next-terminal#218]
官方文档看不懂，能具体出个教程吗？

你看我配置的对吗？
[https://pic.free-img.com/images/2022/01/10/imageb0ed3343fc338318.png](https://pic.free-img.com/images/2022/01/10/imageb0ed3343fc338318.png)
这样连服务器，一直显示等待服务器响应

**Comment by dushixiang** [comment]
> 官方文档看不懂，能具体出个教程吗？
> 
> 你看我配置的对吗？ https://pic.free-img.com/images/2022/01/10/imageb0ed3343fc338318.png 这样连服务器，一直显示等待服务器响应

已确认这是一个bug，将会在下一个版本进行修复。

**Comment by nadirvishun** [comment]
同看不太明白文档，网关是需要另一台服务器？terminal-->网关-->真正要连接的服务器？是这样吗？那我资源中填写的链接信息是网关的信息还是连接的服务器信息？

**Comment by dushixiang** [comment]
> 同看不太明白文档，网关是需要另一台服务器？terminal-->网关-->真正要连接的服务器？是这样吗？那我资源中填写的链接信息是网关的信息还是连接的服务器信息？

填写目标资产的信息
