### ISSUE TITLE
支持Hyper-V宿主机的Preconnection PDU选项

### ISSUE THREAD

**Issue by wjluo** [dushixiang/next-terminal#233]
在Hyper-V虚拟机出网络配置故障时，需要连接到Hyper-V宿主机进行紧急处理。因此，请支持支持Hyper-V宿主机的Preconnection PDU选项。参考文档：https://guacamole.apache.org/doc/gug/configuring-guacamole.html#rdp-preconnection-pdu

**Comment by dushixiang** [comment]
已在 v1.2.7 版本增加此功能。
