### ISSUE TITLE
编辑器加一下文件编码切换

### ISSUE THREAD

**Issue by allcdn** [dushixiang/next-terminal#235]
我程序自带的文件编辑器修改网卡，由于文件编辑器默认是crlf导致重启网卡识别不到一直重启失败，找了三天才知道原因，希望下个版本更新一下

**Comment by zsm1703** [comment]
> 我程序自带的文件编辑器修改网卡，由于文件编辑器默认是crlf导致重启网卡识别不到一直重启失败，找了三天才知道原因，希望下个版本更新一下

已修复：https://github.com/dushixiang/next-terminal/pull/236

您可以自行编译测试
