### ISSUE TITLE
在电脑有多个显示器的情况下，vnc连接没法显示第二块显示器

### ISSUE THREAD

**Issue by 130fanhuan** [dushixiang/next-terminal#237]
在电脑有多个显示器的情况下，vnc连接没法显示第二块显示器，下面也没滚动条往后拉

**Comment by zsm1703** [comment]
> 在电脑有多个显示器的情况下，vnc连接没法显示第二块显示器，下面也没滚动条往后拉

Duplicate of #231 

请查阅 VNC 相关标准
