### ISSUE TITLE
无法使用guacd服务：dial tcp: lookup guacd on 8.8.8.8:53: no such host

### ISSUE THREAD

**Issue by Florance3055** [dushixiang/next-terminal#238]
### 运行guacd
docker run --restart=always --name guacd -d \
  -p 4822:4822 \
  -v ### /www/wwwroot/Application/guacd/data:/usr/local/next-terminal/data \
  dushixiang/guacd:latest

### 运行next-terminal
docker run --restart=always --name next-terminal -d \
  -p 7333:8088 \
  -v /www/wwwroot/Application/next-terminal/data:/usr/local/next-terminal/data \
  -v /etc/localtime:/etc/localtime \
  -e DB=sqlite \
  -e GUACD_HOSTNAME=guacd \
  -e GUACD_PORT=4822 \
  dushixiang/next-terminal:latest \

### ssh的配置
![image](https://user-images.githubusercontent.com/42889572/159114460-636d6978-56d0-4047-b7c9-e0b5828d3257.png)

### guacd日志
guacd[7]: INFO:	Guacamole proxy daemon (guacd) version 1.4.0 started
guacd[7]: INFO:	Listening on host 0.0.0.0, port 4822

### next-terminal日志
建立连接失败: dial tcp: lookup guacd on 8.8.8.8:53: no such host
echo: http: response.WriteHeader on hijacked connection from github.com/labstack/echo/v4.(*Response).WriteHeader (response.go:63)
echo: http: response.Write on hijacked connection from github.com/labstack/echo/v4.(*Response).Write (response.go:75)

**Comment by dushixiang** [comment]
看样子像是你的机器使用了 8.8.8.8 这个dns，在容器里面使用的时候出现了异常，你可以换成 114.114.114.114 试一下。

**Comment by zsm1703** [comment]
> ### 运行guacd
> 
> docker run --restart=always --name guacd -d \
> 
>   -p 4822:4822 \
> 
>   -v ### /www/wwwroot/Application/guacd/data:/usr/local/next-terminal/data \
> 
>   dushixiang/guacd:latest
> 
> 
> 
> ### 运行next-terminal
> 
> docker run --restart=always --name next-terminal -d \
> 
>   -p 7333:8088 \
> 
>   -v /www/wwwroot/Application/next-terminal/data:/usr/local/next-terminal/data \
> 
>   -v /etc/localtime:/etc/localtime \
> 
>   -e DB=sqlite \
> 
>   -e GUACD_HOSTNAME=guacd \
> 
>   -e GUACD_PORT=4822 \
> 
>   dushixiang/next-terminal:latest \
> 
> 
> 
> ### ssh的配置
> 
> ![image](https://user-images.githubusercontent.com/42889572/159114460-636d6978-56d0-4047-b7c9-e0b5828d3257.png)
> 
> 
> 
> ### guacd日志
> 
> guacd[7]: INFO:	Guacamole proxy daemon (guacd) version 1.4.0 started
> 
> guacd[7]: INFO:	Listening on host 0.0.0.0, port 4822
> 
> 
> 
> ### next-terminal日志
> 
> 建立连接失败: dial tcp: lookup guacd on 8.8.8.8:53: no such host
> 
> echo: http: response.WriteHeader on hijacked connection from github.com/labstack/echo/v4.(*Response).WriteHeader (response.go:63)
> 
> echo: http: response.Write on hijacked connection from github.com/labstack/echo/v4.(*Response).Write (response.go:75)

请使用 docker-compose 运行容器，docker run 不支持服务发现的。

**Comment by Florance3055** [comment]
> 请使用 docker-compose 运行容器，docker run 不支持服务发现的。

使用 docker-compose 运行容器 已解决问题，感谢！
