### ISSUE TITLE
请问在debian系统下怎么安装？

### ISSUE THREAD

**Issue by 122al** [dushixiang/next-terminal#243]
next-terminal只支持centos么？在debian系统下应该怎么安装呢（非docker）？

**Comment by zsm1703** [comment]
> next-terminal只支持centos么？在debian系统下应该怎么安装呢（非docker）？

都支持的

**Comment by 122al** [comment]
`root@debian:~# apt install -y libguac-client-kubernetes     libguac-client-rdp     libguac-client-ssh     libguac-client-telnet     libguac-client-vnc     guacd
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package libguac-client-kubernetes
E: Unable to locate package libguac-client-rdp
E: Unable to locate package libguac-client-ssh
E: Unable to locate package libguac-client-telnet
E: Unable to locate package libguac-client-vnc
`

debian下安装libguac这几个软件提示无法找到。。。大佬能给个方法么？搜索引擎上也没找到相关教程

**Comment by dushixiang** [comment]
> `root@debian:~# apt install -y libguac-client-kubernetes libguac-client-rdp libguac-client-ssh libguac-client-telnet libguac-client-vnc guacd Reading package lists... Done Building dependency tree... Done Reading state information... Done E: Unable to locate package libguac-client-kubernetes E: Unable to locate package libguac-client-rdp E: Unable to locate package libguac-client-ssh E: Unable to locate package libguac-client-telnet E: Unable to locate package libguac-client-vnc `
> 
> debian下安装libguac这几个软件提示无法找到。。。大佬能给个方法么？搜索引擎上也没找到相关教程
 
可以参考【Building guacamole-server】章节
https://guacamole.apache.org/doc/gug/installing-guacamole.html
