### ISSUE TITLE
使用动态网关后，查看状态或者操作文件触发

### ISSUE THREAD

**Issue by RabitW** [dushixiang/next-terminal#245]
访问接口500
http://IP:8088/sessions/388424b8-c40c-4222-8209-56986a5afe92/stats

控制台爆错
{"time":"2022-04-13T20:14:25.349306054+08:00","level":"-","prefix":"echo","file":"recover.go","line":"109","message":"[PANIC RECOVER] runtime error: invalid memory address or nil pointer dereference goroutine 431 [running]:\ngithub.com/labstack/echo/v4/middleware.RecoverWithConfig.func1.1.1()\n\t/Users/dushixiang/go/pkg/mod/github.com/labstack/echo/v4@v4.7.0/middleware/recover.go:89 +0x11a\npanic({0xcd0d00, 0x1b9bd40})\n\t/Users/dushixiang/go/go1.17.3/src/runtime/panic.go:1038 +0x215\nnext-terminal/server/api.SessionApi.SessionStatsEndpoint({}, {0x15eb290, 0xc000206280})\n\t/Users/dushixiang/go/src/next-terminal/server/api/session.go:573 +0x2c2\ngithub.com/labstack/echo/v4.(*Echo).add.func1({0x15eb290, 0xc000206280})\n\t/Users/dushixiang/go/pkg/mod/github.com/labstack/echo/v4@v4.7.0/echo.go:520 +0x51\nnext-terminal/server/app.Auth.func1({0x15eb290, 0xc000206280})\n\t/Users/dushixiang/go/src/next-terminal/server/app/middleware.go:127 +0x48c\nnext-terminal/server/app.TcpWall.func1({0x15eb290, 0xc000206280})\n\t/Users/dushixiang/go/src/next-terminal/server/app/middleware.go:39 +0xbc\nnext-terminal/server/app.ErrorHandler.func1({0x15eb290, 0xc000206280})\n\t/Users/dushixiang/go/src/next-terminal/server/app/middleware.go:21 +0x3f\ngithub.com/labstack/echo/v4/middleware.CORSWithConfig.func1.1({0x15eb290, 0xc000206280})\n\t/Users/dushixiang/go/pkg/mod/github.com/labstack/echo/v4@v4.7.0/middleware/cors.go:142 +0x470\ngithub.com/labstack/echo/v4/middleware.RecoverWithConfig.func1.1({0x15eb290, 0xc000206280})\n\t/Users/dushixiang/go/pkg/mod/github.com/labstack/echo/v4@v4.7.0/middleware/recover.go:115 +0x10a\ngithub.com/labstack/echo/v4.(*Echo).ServeHTTP(0xc00056c900, {0x15c8940, 0xc00046a540}, 0xc0000b0900)\n\t/Users/dushixiang/go/pkg/mod/github.com/labstack/echo/v4@v4.7.0/echo.go:630 +0x3bc\nnet/http.serverHandler.ServeHTTP({0xc000618480}, {0x15c8940, 0xc00046a540}, 0xc0000b0900)\n\t/Users/dushixiang/go/go1.17.3/src/net/http/server.go:2878 +0x43b\nnet/http.(*conn).serve(0xc00025c1e0, {0x15ccd00, 0xc00069a390})\n\t/Users/dushixiang/go/go1.17.3/src/net/http/server.go:1929 +0xb08\ncreated by net/http.(*Server).Serve\n\t/Users/dushixiang/go/go1.17.3/src/net/http/server.go:3033 +0x4e8\n\ngoroutine 1 [IO wait]:\ninternal/poll.runtime_pollWait(0x7f644097d608, 0x72)\n\t/Users/dushixiang/go/go1.17.3/src/runtime/netpoll.go:234 +0x89\ninternal/poll.(*pollDesc).wait(0xc000592d00, 0xc000000340, 0x0)\n\t/Users/dushixiang/go/go1.17.3/src/internal/poll/fd_poll_runtime.go:84 +0x32\ninternal/poll.(*pollDesc).waitRead(...)\n\t/Users/dushixiang/go/go1.17.3/src/internal/poll/fd_poll_runtime.go:89\ninternal/poll.(*FD).Accept(0xc000592d00)\n\t/Users/dushixiang/go/go1.17.3/src/internal/poll/fd_unix.go:402 +0x22c\nnet.(*netFD).accept(0xc000592d00)\n\t/Users/dushixiang/go/go1.17.3/src/net/fd_unix.go:173 +0x35\nnet.(*TCPListener).accept(0xc000a13410)\n\t/Users/dushixiang/go/go1.17.3/src/net/tcpsock_posix.go:140 +0x28\nnet.(*TCPListener).AcceptTCP(0xc000a13410)\n\t/Users/dushixiang/go/go1.17.3/src/net/tcpsock.go:249 +0x3d\ngithub.com/labstack/echo/v4.tcpKeepAliveListener.Accept({0xc000a0fd48})\n\t/Users/dushixiang/go/pkg/mod/github.com/labstack/echo/v4@v4.7.0/echo.go:939 +0x1d\nnet/http.(*Server).Serve(0xc00046a000, {0x15c7c20, 0xc0001353a8})\n\t/Users/dushixiang/go/go1.17.3/src/net/http/server.go:3001 +0x394\ngithub.com/labstack/echo/v4.(*Echo).Start(0xc00056c900, {0xc00013ada0, 0xc})\n\t/Users/dushixiang/go/pkg/mod/github.com/labstack/echo/v4@v4.7.0/echo.go:647 +0xce\nnext-terminal/server/app.Run()\n\t/Users/dushixiang/go/src/next-terminal/server/app/app.go:130 +0x29c\nmain.main()\n\t/Users/dushixiang/go/src/next-terminal/main.go:10 +0x19\n\ngoroutine 14 [select, 75 minutes]:\ndatabase/sql.(*DB).connectionOpener(0xc000276340, {0x15ccc58, 0xc0003989c0})\n\t/Users/dushixiang/go/go1.17.3/src/database/sql/sql.go:1196 +0x93\ncreated by database/sql.OpenDB\n\t/Users/dushixiang/go/go1.17.3/src/database/sql/sql.go:794 +0x188\n\ngoroutine 15 [select, 7 minutes]:\ngithub.com/patrickmn/go-cache.(*janitor).Run(0xc00090a4f0, 0x0)\n\t/Users/dushixiang/go/pkg/mod/github.com/patrickmn/go-cache@v2.1.0+incompatible/cache.go:1079 +0x89\ncreated by github.com/patrickmn/go-cache.runJanitor\n\t/Users/dushixiang/go/pkg/mod/github.com/patrickmn/go-cache@v2.1.0+incompatible/cache.go:1099 +0xf2\n\ngoroutine 16 [select, 7 minutes]:\ngithub.com/patrickmn/go-cache.(*janito\n"}

**Comment by zsm1703** [comment]
> ang/go/src/next-terminal/main.

请问版本是多少？测试没有复现该问题
![image](https://user-images.githubusercontent.com/8140841/163194791-26d815d6-2723-4917-8853-495d8165656e.png)

![image](https://user-images.githubusercontent.com/8140841/163194822-a4816e0d-87f2-422e-9e34-0790d0af8fe0.png)

**Comment by RabitW** [comment]
资产为linux环境是，点击接入后，点击状态，或者文件管理功能
![image](https://user-images.githubusercontent.com/9126788/163201407-c9abd8b4-e853-494a-be59-326ac3304db8.png)
![image](https://user-images.githubusercontent.com/9126788/163201530-207f2f4d-7e22-4d1a-9e5e-0a73082c0e42.png)
使用的是最新的v1.2.6-beta2

**Comment by RabitW** [comment]
我是按原生方式部署的



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年04月13日 21:47 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [dushixiang/next-terminal] 使用动态网关后，查看状态或者操作文件触发 (Issue #245) |

ang/go/src/next-terminal/main.

请问版本是多少？测试没有复现该问题

**Comment by zsm1703** [comment]
> 资产为linux环境是，点击接入后，点击状态，或者文件管理功能 ![image](https://user-images.githubusercontent.com/9126788/163201407-c9abd8b4-e853-494a-be59-326ac3304db8.png) ![image](https://user-images.githubusercontent.com/9126788/163201530-207f2f4d-7e22-4d1a-9e5e-0a73082c0e42.png) 使用的是最新的v1.2.6-beta2

---

<img width="446" alt="image" src="https://user-images.githubusercontent.com/8140841/163298619-02da7541-46f8-43ec-b83d-90d1024bc579.png">
找群主加下微信群吧，了解下环境

**Comment by dushixiang** [comment]
已在 v1.2.7 版本修复此问题。
