### ISSUE TITLE
使用docker搭建，IP访问可连接，使用域名访问失败

### ISSUE THREAD

**Issue by chichdeng** [dushixiang/next-terminal#246]
2022-04-16 20:04:36 ERROR [logrus.(*Entry).Logf:314]升级为WebSocket协议失败：websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header
echo: http: superfluous response.WriteHeader call from github.com/labstack/echo/v4.(*Response).WriteHeader (response.go:63)
2022-04-16 20:05:55 ERROR [logrus.(*Entry).Logf:314]升级为WebSocket协议失败：websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header
echo: http: superfluous response.WriteHeader call from github.com/labstack/echo/v4.(*Response).WriteHeader (response.go:63)

**Comment by chichdeng** [comment]
抱歉，是我未配置反向代理问题，已经可以正常使用。
但是主要就是复制到剪切板的文字，无法在服务器内粘贴使用。

**Comment by dushixiang** [comment]
> 抱歉，是我未配置反向代理问题，已经可以正常使用。 但是主要就是复制到剪切板的文字，无法在服务器内粘贴使用。

需要开启 https 。

**Comment by chichdeng** [comment]
![image](https://user-images.githubusercontent.com/17406256/163674770-95020665-8ae4-4492-a7ee-29797f88a8bb.png)
SSL已经开启的

**Comment by chichdeng** [comment]
呃，或者可能是我描述的问题，我在本机复制，他可以出现在Next Terminal 页面的 剪贴板 里面。
但是我如何把他粘贴到服务器内呢？

**Comment by dushixiang** [comment]
> ![image](https://user-images.githubusercontent.com/17406256/163674770-95020665-8ae4-4492-a7ee-29797f88a8bb.png) SSL已经开启的

Windows正常的Ctrl+V或者右键选择粘贴，ssh右键即可。

**Comment by chichdeng** [comment]
> > ![image](https://user-images.githubusercontent.com/17406256/163674770-95020665-8ae4-4492-a7ee-29797f88a8bb.png) SSL已经开启的
> 
> Windows正常的Ctrl+V或者右键选择粘贴，ssh右键即可。

![image](https://user-images.githubusercontent.com/17406256/163674978-afd018bb-6dd9-43b4-8f87-3c67d5e6b86e.png)
无法粘贴出本机的内容，剪贴板里面已经有复制的内容了。
在服务器内，图片内的文字 Googke Chrome ，是在服务器内复制的。
无法把剪贴板内的粘贴到服务器。

**Comment by chichdeng** [comment]
测试SSH链接可以直接右键粘贴，但是Windows不可以。

**Comment by dushixiang** [comment]
> 测试SSH链接可以直接右键粘贴，但是Windows不可以。

windows 是右键打开『右键菜单』，点击『粘贴』。
