### ISSUE TITLE
windows的的RDP管理方式页面缩放次数过多导致会话被锁定

### ISSUE THREAD

**Issue by RabitW** [dushixiang/next-terminal#257]
windows的的RDP管理方式页面缩放次数过多导致会话被锁定
一方面是会重复链接
![image](https://user-images.githubusercontent.com/9126788/169435508-8b5f7037-7a4e-4e69-b7dc-46c754e08695.png)
调整次数过多后就锁死
![image](https://user-images.githubusercontent.com/9126788/169435603-ef87cbda-e218-4083-9602-e0cb4e943921.png)
测试gucad能同屏缩放，不再重新登录
![image](https://user-images.githubusercontent.com/9126788/169435659-93aad37f-4c05-4ddb-ba56-a718e0b0fb5a.png)

**Comment by dushixiang** [comment]
> windows的的RDP管理方式页面缩放次数过多导致会话被锁定 一方面是会重复链接 ![image](https://user-images.githubusercontent.com/9126788/169435508-8b5f7037-7a4e-4e69-b7dc-46c754e08695.png) 调整次数过多后就锁死 ![image](https://user-images.githubusercontent.com/9126788/169435603-ef87cbda-e218-4083-9602-e0cb4e943921.png) 测试gucad能同屏缩放，不再重新登录 ![image](https://user-images.githubusercontent.com/9126788/169435659-93aad37f-4c05-4ddb-ba56-a718e0b0fb5a.png)

安装 Windows 的补丁可修复此问题，详情请参考 https://support.microsoft.com/zh-cn/topic/%E6%97%A0%E6%B3%95%E5%B0%86%E8%BF%9C%E7%A8%8B%E6%A1%8C%E9%9D%A2%E6%9C%8D%E5%8A%A1%E4%BC%9A%E8%AF%9D%E9%87%8D%E6%96%B0%E5%BB%BA%E7%AB%8B%E5%88%B0%E5%9F%BA%E4%BA%8E-windows-server-2008-r2-%E7%9A%84%E6%9C%8D%E5%8A%A1%E5%99%A8-cf0965d1-e36c-b9d0-474c-ca894606ed57

**Comment by dushixiang** [comment]
已在v1.3.0版本修改页面缩放策略。
