### ISSUE TITLE
web终端显示中文时乱码

### ISSUE THREAD

**Issue by careylipu** [dushixiang/next-terminal#258]
root@ee1c8095abc0:~# curl cip.cc
IP: 82.157.160.150
地址: 中国  中国

数据二: 北京市 | 腾讯云

数据三: 中国北京北京 | 电信

URL: http://www.cip.cc/82.157.160.150
root@ee1c8095abc0:~# 

![image](https://user-images.githubusercontent.com/15045646/169651645-e1a8a0f4-14a2-4c55-9295-407b8c03a7df.png)

**Comment by 4Aiur** [comment]
操作系统没有中文字体 https://github.com/dushixiang/next-terminal/issues/200
