### ISSUE TITLE
docker 部署版本总是Version:0.4.1

### ISSUE THREAD

**Issue by careylipu** [dushixiang/next-terminal#259]
Next Terminal ©2021 dushixiang Version:0.4.1

**Comment by dushixiang** [comment]
> Next Terminal ©2021 dushixiang Version:0.4.1

您应该是使用了第三方的docker镜像源，latest 被缓存了，您可以去除掉第三方的docker镜像源或者指定版本号进行拉取。

**Comment by dushixiang** [comment]
太久没有回复，暂时关闭此 issues，后续如果有问题可再次打开。
