### ISSUE TITLE
RDP老是出现“连接已关闭”

### ISSUE THREAD

**Issue by moeik** [dushixiang/next-terminal#265]
一直连不上去 

本地用远程连接又没有问题

可能是什么原因?

**Comment by dushixiang** [comment]
> 一直连不上去 
> 
> 
> 
> 本地用远程连接又没有问题
> 
> 
> 
> 可能是什么原因?

可以查看一下 guacd 服务的日志

**Comment by sshuangliu** [comment]
> 
如果是通过反向代理，websocket 是否开启，检查下

**Comment by dushixiang** [comment]
太久没有回复，暂时关闭此 issues，后续如果有问题可再次打开。
