### ISSUE TITLE
自己编译后,rdp无法使用

### ISSUE THREAD

**Issue by JustTestCode** [dushixiang/next-terminal#270]
丢失
`const sink = new Guacamole.InputSink()`

没有InputSink方法

![Screenshot_1658608588](https://user-images.githubusercontent.com/65500757/180622030-df65523e-9a2f-4d19-9583-dda0c3492fff.png)

**Comment by dushixiang** [comment]
> 丢失 `const sink = new Guacamole.InputSink()`
> 
> 没有InputSink方法
> 
> ![Screenshot_1658608588](https://user-images.githubusercontent.com/65500757/180622030-df65523e-9a2f-4d19-9583-dda0c3492fff.png)

升级一下 guacamole-common-js 试试，最新版是 1.4.0-a

https://www.npmjs.com/package/guacamole-common-js

**Comment by dushixiang** [comment]
太久没有回复，暂时关闭此 issues，后续如果有问题可再次打开。
