### ISSUE TITLE
SSH资产无法使用右键复制或Ctrl+C复制

### ISSUE THREAD

**Issue by wdwnet** [dushixiang/next-terminal#273]
SSH资产，连接模式为Native，连接后，在命令行无法复制内容，版本1.2.7
![image](https://user-images.githubusercontent.com/73337439/182311714-8cc04c9f-a789-4221-be31-c63ef8d86d6e.png)

**Comment by avrileader** [comment]
要https

**Comment by dushixiang** [comment]
> SSH资产，连接模式为Native，连接后，在命令行无法复制内容，版本1.2.7
> 
> ![image](https://user-images.githubusercontent.com/73337439/182311714-8cc04c9f-a789-4221-be31-c63ef8d86d6e.png)

此问题已确认，将在下一个版本中进行修复。

**Comment by dushixiang** [comment]
已在 v1.3.0 版本修复。
