### ISSUE TITLE
首次进入js加载要40秒

### ISSUE THREAD

**Issue by EthanChenLi** [dushixiang/next-terminal#275]
Version:1.2.7

<img width="829" alt="image" src="https://user-images.githubusercontent.com/6337626/183085037-fbb280c2-f702-4f59-8bab-3b1991c4a658.png">

这个版本登陆页面的js有5m大，记载要40秒，有解决办法吗。 除了cdn

**Comment by dushixiang** [comment]
> Version:1.2.7
> 
> 
> 
> <img width="829" alt="image" src="https://user-images.githubusercontent.com/6337626/183085037-fbb280c2-f702-4f59-8bab-3b1991c4a658.png">
> 
> 
> 
> 这个版本登陆页面的js有5m大，记载要40秒，有解决办法吗。 除了cdn

此问题已确认，将在下一个版本中进行优化，异步加载每一个页面，不再打包在一个js文件中。

**Comment by yuanqiyong** [comment]
> Version:1.2.7
> 
> <img alt="image" width="829" src="https://user-images.githubusercontent.com/6337626/183085037-fbb280c2-f702-4f59-8bab-3b1991c4a658.png">
> 
> 这个版本登陆页面的js有5m大，记载要40秒，有解决办法吗。 除了cdn

确实，5M太夸张了，期待作者@dushixiang下次更新

**Comment by EthanChenLi** [comment]
> 

大佬什么时候发新版本呀。。  每天都来看看更新了没

**Comment by dushixiang** [comment]
> > 
> 
> 大佬什么时候发新版本呀。。 每天都来看看更新了没

工作太忙，凡事太多，还需要等待一段时间。

**Comment by dushixiang** [comment]
已在 v1.3.0 版本修复此问题。
