### ISSUE TITLE
docker版本next-terminal容器总是重启

### ISSUE THREAD

**Issue by RookieTerry** [dushixiang/next-terminal#277]
如下图：
![image](https://user-images.githubusercontent.com/77920425/184909821-78dcec5f-6e90-4b26-9492-fd2506fff531.png)

**Comment by yuanqiyong** [comment]
> 如下图： ![image](https://user-images.githubusercontent.com/77920425/184909821-78dcec5f-6e90-4b26-9492-fd2506fff531.png)

你以非后台方式启动，看看日志，肯定会有报错日志的。

**Comment by yuanqiyong** [comment]
> 

这个主要是使用宿主机证书，可以百度下：ssh 证书登录。
如果你需要next-terminal跳板机终端 和 宿主机终端一样 证书登录可以加上。
如果你不需要，可以把这行注释掉。
![无标题](https://user-images.githubusercontent.com/13116322/185549654-96a75125-db27-4da0-85b9-7ab90acf5892.png)

**Comment by RookieTerry** [comment]
容器启动成功了，web管理页面应该访问哪个端口呢？

**Comment by RookieTerry** [comment]
> > 
> 
> 这个主要是使用宿主机证书，可以百度下：ssh 证书登录。 如果你需要next-terminal跳板机终端 和 宿主机终端一样 证书登录可以加上。 如果你不需要，可以把这行注释掉。 ![无标题](https://user-images.githubusercontent.com/13116322/185549654-96a75125-db27-4da0-85b9-7ab90acf5892.png)

容器启动成功了，web管理页面应该访问哪个端口呢？

**Comment by kt1024** [comment]
> > > 
> > 
> > 
> > 这个主要是使用宿主机证书，可以百度下：ssh 证书登录。 如果你需要next-terminal跳板机终端 和 宿主机终端一样 证书登录可以加上。 如果你不需要，可以把这行注释掉。 ![无标题](https://user-images.githubusercontent.com/13116322/185549654-96a75125-db27-4da0-85b9-7ab90acf5892.png)
> 
> 容器启动成功了，web管理页面应该访问哪个端口呢？

8088

**Comment by kt1024** [comment]
`docker ps` 看看运行状况和有没有端口映射，`docker logs <容器名字>` 看日志有没有错误

**Comment by RookieTerry** [comment]
> `docker ps` 看看运行状况和有没有端口映射，`docker logs <容器名字>` 看日志有没有错误

 ERROR [logrus.(*Entry).Logf:314]连接数据库异常: dial tcp ip:3306: i/o timeout
MySQL数据库在另外一台vps上，但是设置了白名单ip，为什么会访问不了呢？

**Comment by kt1024** [comment]
是不是用了mysql root user? root默认禁止外部访问的.

**Comment by RookieTerry** [comment]
请问https访问怎么开启？
