### ISSUE TITLE
安装出现问题怎么办？CENTOS7系统

### ISSUE THREAD

**Issue by mp1802174** [dushixiang/next-terminal#29]
[root@instance-20200301-1311 /]# yum install -y gcc cairo-devel libjpeg-turbo-devel libpng-devel uuid-devel freerdp-devel pango-devel libssh2-devel libtelnet-devel libvncserver-devel pulseaudio-libs-devel openssl-devel libvorbis-devel libwebp-devel libwebsockets-devel libtool
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: ty1.mirror.newmediaexpress.com
 * epel: mirrors.thzhost.com
 * extras: ty1.mirror.newmediaexpress.com
 * nux-dextop: li.nux.ro
 * updates: ty1.mirror.newmediaexpress.com
Package gcc-4.8.5-44.el7.x86_64 already installed and latest version
Package cairo-devel-1.15.12-4.el7.x86_64 already installed and latest version
Package libjpeg-turbo-devel-1.2.90-8.el7.x86_64 already installed and latest version
Package 2:libpng-devel-1.5.13-8.el7.x86_64 already installed and latest version
Package uuid-devel-1.6.2-26.el7.x86_64 already installed and latest version
Package freerdp-devel-2.1.1-2.el7.x86_64 already installed and latest version
Package pango-devel-1.42.4-4.el7_7.x86_64 already installed and latest version
Package libssh2-devel-1.8.0-4.el7.x86_64 already installed and latest version
Package libtelnet-devel-0.23-1.el7.x86_64 already installed and latest version
Package libvncserver-devel-0.9.9-14.el7_8.1.x86_64 already installed and latest version
Package pulseaudio-libs-devel-10.0-6.el7_9.x86_64 already installed and latest version
Package 1:openssl-devel-1.0.2k-21.el7_9.x86_64 already installed and latest version
Package 1:libvorbis-devel-1.3.3-8.el7.1.x86_64 already installed and latest version
Package libwebp-devel-0.3.0-7.el7.x86_64 already installed and latest version
Package libwebsockets-devel-3.0.1-2.el7.x86_64 already installed and latest version
Package libtool-2.4.2-22.el7_3.x86_64 already installed and latest version
Nothing to do

[root@instance-20200301-1311 /]# tar -xzf guacamole-server-1.2.0.tar.gz
[root@instance-20200301-1311 /]# cd guacamole-server-1.2.0
[root@instance-20200301-1311 guacamole-server-1.2.0]# ./configure --with-init-dir=/etc/init.d
checking for a BSD-compatible install... /bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... printf
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /bin/ld
checking if the linker (/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /bin/nm -B
checking the name lister (/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking how to run the C preprocessor... /lib/cpp
configure: error: in `/guacamole-server-1.2.0':
configure: error: C preprocessor "/lib/cpp" fails sanity check
See `config.log' for more details
以上为提示，看不懂哪里有问题

**Comment by dushixiang** [comment]
应该是缺少了c++的依赖库
```
yum install gcc-c++
```

**Comment by mp1802174** [comment]
> yum install gcc-c++

[root@instance-20200301-1311 next-terminal-flake-nix]# yum install gcc-c++
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: mirrors.aliyun.com
 * epel: ftp.riken.jp
 * extras: mirrors.aliyun.com
 * nux-dextop: mirror.li.nux.ro
 * updates: mirrors.aliyun.com
Package gcc-c++-4.8.5-44.el7.x86_64 already installed and latest version
Nothing to do
已经安装了，好象不是这个原因

**Comment by dushixiang** [comment]
yum install glibc-headers
