### ISSUE TITLE
遇到两个bug

### ISSUE THREAD

**Issue by hausen1012** [dushixiang/next-terminal#291]
前提: docker最新版本安装，sqlite数据库

1、登录不自动进行跳转，需要删除 login后缀再次刷新
2、导入主机不可以ssh，即使密码正确。但是点击编辑，不修改任何内容，点击确定，再次连接即可连接

**Comment by dushixiang** [comment]
第一个问题已在1.3.0-beta3修复。

**Comment by herimvane** [comment]
刚试了，docker安装登录还是无法跳转。

**Comment by herimvane** [comment]
> 第一个问题已在1.3.0-beta3修复。

刚试了，docker安装登录还是无法跳转。

**Comment by dushixiang** [comment]
第二个问题已在 1.3.0 正式版本修复。
