### ISSUE TITLE
如何在未登录的情况下关闭双因素认证？

### ISSUE THREAD

**Issue by EthanChenLi** [dushixiang/next-terminal#292]
之前的手机掉了，从新下载了Authenticator 发现并没有next-terminal的验证码。 如何取消解绑呢

**Comment by dushixiang** [comment]
> 之前的手机掉了，从新下载了Authenticator 发现并没有next-terminal的验证码。 如何取消解绑呢

进入到 next-terminal 二进制所在目录，执行下面的命令。
```
./next-terminal --reset-totp admin
```
