### ISSUE TITLE
docker v1.3.0 : 您的访问请求被拒绝 :(

### ISSUE THREAD

**Issue by 0x9394** [dushixiang/next-terminal#293]
digest: 5cf92d47f5b2
docker logs 一推提示`重新加载用户授权Token`
重启浏览器不行，所有电脑都是进不去，退回1.2.7后正常。

**Comment by 0x9394** [comment]
授权全部清零，还好DB有备份不用重来。

**Comment by dushixiang** [comment]
> 授权全部清零，还好DB有备份不用重来。

请问您用的是admin类型的用户登录的吗？

另外授权全部清零是因为更换了数据库表。

**Comment by 0x9394** [comment]
> > 授权全部清零，还好DB有备份不用重来。
> 
> 请问您用的是admin类型的用户登录的吗？
> 
> 另外授权全部清零是因为更换了数据库表。

是admin登录，发现其他用户的授权都清零了
