### ISSUE TITLE
批量导入模板格式有误

### ISSUE THREAD

**Issue by fcwys** [dushixiang/next-terminal#297]
批量导入的模板csv文件内不是用逗号进行分割，建议修复下模板文件，谢谢！

**Comment by dushixiang** [comment]
> 批量导入的模板csv文件内不是用逗号进行分割，建议修复下模板文件，谢谢！

目前是使用逗号分隔的，英文逗号「,」。

**Comment by fcwys** [comment]
意思是模板下载链接下载的文件里面是空格分割的
