### ISSUE TITLE
历史会话只显示一页

### ISSUE THREAD

**Issue by vicacheung** [dushixiang/next-terminal#299]
如图，通过筛选能显示出其他会话，但不管怎么设置都只有一页。
原来是 **1.2.7** 升级到 **1.3.1** 后还是这样。
[![xHCJq1.png](https://s1.ax1x.com/2022/11/02/xHCJq1.png)](https://imgse.com/i/xHCJq1)

**Comment by dushixiang** [comment]
> 如图，通过筛选能显示出其他会话，但不管怎么设置都只有一页。 原来是 **1.2.7** 升级到 **1.3.1** 后还是这样。 [![xHCJq1.png](https://camo.githubusercontent.com/18b39b8e88d98ea88381c264c3e799b25f6c5882802185cf566a23e6ab3bc8ca/68747470733a2f2f73312e617831782e636f6d2f323032322f31312f30322f7848434a71312e706e67)](https://imgse.com/i/xHCJq1)

这个我没办法复现，你可以加群反馈一下具体情况。
