### ISSUE TITLE
docker启动后打开界面显示连接请求被拒绝

### ISSUE THREAD

**Issue by Theresa142** [dushixiang/next-terminal#3]
docker ps返回结果:
```
CONTAINER ID   IMAGE                            COMMAND                  CREATED          STATUS          PORTS                               NAMES
ce40e3a01742   dushixiang/next-terminal:0.0.1   "/bin/sh -c /usr/bin…"   30 seconds ago   Up 29 seconds   4822/tcp, 0.0.0.0:8088->8088/tcp    next-terminal
```
配置文件:
```
$ cat <<EOF >> /etc/next-terminal/config.yaml
mysql:
  hostname: 127.0.0.1
  port: 3306
  username: root
  password: root
  database: next_terminal
server:
  addr: 0.0.0.0:8088
EOF
```
docker启动命令:
```
$ docker run -d \
>   -p 8088:8088 \
>   -v /etc/next-terminal/config.yaml:/etc/next-terminal/config.yaml \
>   -v /etc/next-terminal/recording/:/usr/local/next-terminal/recording/ \
>   -v /etc/next-terminal/drive/:/usr/local/next-terminal/drive/ \
>   --name next-terminal \
>   --restart always dushixiang/next-terminal:0.0.1
```

**Comment by dushixiang** [comment]
因为docker容器内部访问宿主机上的mysql IP不是127.0.0.1，可以使用 ifconfig 或者 ipconfig查看，通常网桥docker0的IP是172.1.0.1，或者使用宿主机的局域网地址也是可以的。

**Comment by jackwen999** [comment]
hostname: 填宿主机外网IP可以解决
@dushixiang 大哥，我发的第一条issue 有看到吗？

**Comment by Theresa142** [comment]
> 因为docker容器内部访问宿主机上的mysql IP不是127.0.0.1，通常网桥docker0的IP是172.1.0.1，或者使用宿主机的局域网地址也是可以的，使用 ifconfig 或者 ipconfig查看。

那如果是docker容器的MySQL呢?
也是172.1.0.1吗?

**Comment by dushixiang** [comment]
> > 因为docker容器内部访问宿主机上的mysql IP不是127.0.0.1，通常网桥docker0的IP是172.1.0.1，或者使用宿主机的局域网地址也是可以的，使用 ifconfig 或者 ipconfig查看。
> 
> 那如果是docker容器的MySQL呢?
> 也是172.1.0.1吗?

使用另一个容器内的mysql请使用 
`--link mysql容器名称` 
配置文件mysql服务器地址为 `mysql容器名称`

**Comment by Theresa142** [comment]
如果另一个容器名称就叫mysql就只需要` --link mysql`就可以了是吗

**Comment by Theresa142** [comment]
还是要写mysqlmysql

**Comment by jackwen999** [comment]
`$ cat <<EOF >> /etc/next-terminal/config.yaml
mysql:
  hostname: 你的mysql容器名称
  port: 3306
  username: root
  password: root
  database: next_terminal
server:
  addr: 0.0.0.0:8088
EOF`
