### ISSUE TITLE
BUG：RDP点击剪贴板弹框后返回无法使用键盘输入

### ISSUE THREAD

**Issue by fcwys** [dushixiang/next-terminal#304]
RDP点击剪贴板弹框后返回无法使用键盘输入，经测试是由于剪贴板按钮处于激活状态导致桌面失去焦点，希望剪贴板在点击确定或者取消按钮后去除剪贴板按钮的激活状态。
如图：
![image](https://user-images.githubusercontent.com/28641034/200180229-b48bd8f6-c50f-4af2-9af6-120bd73a9e65.png)

**Comment by fcwys** [comment]
经过测试v1.3.4版本仍然存在此问题，粘贴板按钮并未自动失焦
![image](https://user-images.githubusercontent.com/28641034/202941118-e700ee3f-77c1-42f8-9d32-5b72d0e0d52f.png)

**Comment by dushixiang** [comment]
v1.3.5 修复了此问题。
