### ISSUE TITLE
Bug：docker部署，会话来源IP不显示用户真实地址，均为类似172.20.0.1的地址。

### ISSUE THREAD

**Issue by herimvane** [dushixiang/next-terminal#305]

**Comment by dushixiang** [comment]
> _No description provided._

建议加一层nginx在外部进行反向代理，因为在docker中网络是经过了多次转发，docker内部利用 iptables 的DNAT功能。

**Comment by dushixiang** [comment]
长时间未回复，先关闭此问题，如果后续有疑问再打开。
