### ISSUE TITLE
增加sshd日志输出

### ISSUE THREAD

**Issue by Silentely** [dushixiang/next-terminal#308]
请问通过sshd服务有登陆日志输出么？类似宿主机/var/log/auth.log。本意想通过fail2ban保护sshd服务端口，遗憾的是没有找到sshd的登陆日志。

**Comment by dushixiang** [comment]
> 请问通过sshd服务有登陆日志输出么？类似宿主机/var/log/auth.log。本意想通过fail2ban保护sshd服务端口，遗憾的是没有找到sshd的登陆日志。

暂时没有输出到日志，在登录日志中浏览器类型为「terminal」的是sshd登录日志。
