### ISSUE TITLE
feature：1、资产列表展示设置   2、双因素认证光标

### ISSUE THREAD

**Issue by toyqiu** [dushixiang/next-terminal#311]
1.1、资产列表展示我记得前几个版本可以展示一页显示多少条的，现在只能翻页不能展示多条了
1.2、资产列表默认顺序是最新新建的资产显示在最前，可是我最常用的是最早新建的，要么需要翻页，要么多按一下按时间排序，希望能有个固定选项，刷新完又恢复新建的资产显示在最前。

2、双因素认证光标前几版本是账号密码输入完点击登陆后光标自动落在双因验证对话框内，现在需要用鼠标点一下。我用密码管理器输入的，自动填充登陆后还要再点一下双因验证对话框真的心态会炸

**Comment by dushixiang** [comment]
> 1.1、资产列表展示我记得前几个版本可以展示一页显示多少条的，现在只能翻页不能展示多条了 1.2、资产列表默认顺序是最新新建的资产显示在最前，可是我最常用的是最早新建的，要么需要翻页，要么多按一下按时间排序，希望能有个固定选项，刷新完又恢复新建的资产显示在最前。
> 
> 2、双因素认证光标前几版本是账号密码输入完点击登陆后光标自动落在双因验证对话框内，现在需要用鼠标点一下。我用密码管理器输入的，自动填充登陆后还要再点一下双因验证对话框真的心态会炸

非常感谢你的反馈，这些问题将在下一个版本进行修复。
