### ISSUE TITLE
建议兼容手机端

### ISSUE THREAD

**Issue by einsqing** [dushixiang/next-terminal#316]
建议兼容一下手机端，如果觉得工作量大，而且没有必要，可以固定宽，比如1200px，在手机上能左右滑动正常展示就行，现在手机打开没法用![Screenshot_20221122_002244_com.quark.browser.jpg](https://user-images.githubusercontent.com/7685948/203106128-60f5ab73-e988-4e82-9df1-ad3319bd7c66.jpg)

**Comment by dushixiang** [comment]
> 建议兼容一下手机端，如果觉得工作量大，而且没有必要，可以固定宽，比如1200px，在手机上能左右滑动正常展示就行，现在手机打开没法用![Screenshot_20221122_002244_com.quark.browser.jpg](https://user-images.githubusercontent.com/7685948/203106128-60f5ab73-e988-4e82-9df1-ad3319bd7c66.jpg)

暂时应该不会兼容手机端。
