### ISSUE TITLE
文件上传速度慢

### ISSUE THREAD

**Issue by maxzhao-it** [dushixiang/next-terminal#317]
服务器 SCP 远程主机速度很快 10MB/s，使用软件上传速度很慢，400KB/s，这个有没有办法解决？

**Comment by dushixiang** [comment]
> 服务器 SCP 远程主机速度很快 10MB/s，使用软件上传速度很慢，400KB/s，这个有没有办法解决？

```
你的电脑 ---- 10MB/s ----> 远程主机
你的电脑 ---- 400KB/s ----> Next Terminal ---- ??KB/s ---->远程主机
```

**Comment by maxzhao-it** [comment]
我的电脑 ---- 80MB/s ----> Next Terminal 服务器  ----> 10MB/s ----> 远程主机 
Next Terminal web ---- 3~6MB/s ----> Next Terminal ----> 400KB/s ---->远程主机
大概是这个样子，使用的nethogs 监控的 Next Terminal 服务器 下的 Next Terminal 进程。

**Comment by dushixiang** [comment]
> 我的电脑 ---- 80MB/s ----> Next Terminal 服务器 ----> 10MB/s ----> 远程主机 Next Terminal web ---- 3~6MB/s ----> Next Terminal ----> 400KB/s ---->远程主机 大概是这个样子，使用的nethogs 监控的 Next Terminal 服务器 下的 Next Terminal 进程。

你可以测试一下「磁盘空间」那里上传速度是多少，这个是直接写到服务器硬盘上的。
