### ISSUE TITLE
为什么打开IP显示404？

### ISSUE THREAD

**Issue by as564335sa** [dushixiang/next-terminal#318]
系统是ubuntu，按照文档，原生安装，打开程序成功，输入IP和端口却提示404 page not found？直接执行进程和systemd执行都是404,WorkingDirectory也是设置了的？

**Comment by dushixiang** [comment]
> 系统是ubuntu，按照文档，原生安装，打开程序成功，输入IP和端口却提示404 page not found？直接执行进程和systemd执行都是404,WorkingDirectory也是设置了的？

你用的是哪个版本？

**Comment by as564335sa** [comment]
最新的release版，刚刚的1.3.5也试了，一样的结果，
![image](https://user-images.githubusercontent.com/35949162/204288044-3da8017e-e7b1-4a23-a996-27fe87a572ec.png)
![image](https://user-images.githubusercontent.com/35949162/204288116-32a4ba55-278c-4ab6-9002-8e754f33b364.png)

**Comment by as564335sa** [comment]
> > 系统是ubuntu，按照文档，原生安装，打开程序成功，输入IP和端口却提示404 page not found？直接执行进程和systemd执行都是404,WorkingDirectory也是设置了的？
> 
> 你用的是哪个版本？

**Comment by dushixiang** [comment]
> > > 系统是ubuntu，按照文档，原生安装，打开程序成功，输入IP和端口却提示404 page not found？直接执行进程和systemd执行都是404,WorkingDirectory也是设置了的？
> > 
> > 
> > 你用的是哪个版本？

你这是本地启动的吧？前端是独立的，在web文件夹下，create-react-app 创建。

**Comment by as564335sa** [comment]
> 

额好吧，我还以为前端是打包到bin里的，晓得了
