### ISSUE TITLE
会话无法维持，1分钟左右自动断开

### ISSUE THREAD

**Issue by killbus** [dushixiang/next-terminal#32]
![FireShot Capture 005 - Next Terminal](https://user-images.githubusercontent.com/358214/104716340-c8128300-5762-11eb-9aca-b63f5a1287ef.png)

**部署方式：**

```
docker run -d \
  -p 8088:8088 \
  --name next-terminal \
  --restart always ghcr.io/dushixiang/next-terminal:latest
```

我在本机及服务器上均部署测试。接入后，跑 `top`，会话无法维持 1 分钟。

**Comment by dushixiang** [comment]
感谢反馈，已经临时修复。
