### ISSUE TITLE
系统监控页每秒访问数太大，waf给屏蔽了。

### ISSUE THREAD

**Issue by woall** [dushixiang/next-terminal#325]
系统监控页面单ip每秒访问量10-20次，太高了，waf给屏蔽了。建议改到每秒1次就足够了。

**Comment by dushixiang** [comment]
> 系统监控页面单ip每秒访问量10-20次，太高了，waf给屏蔽了。建议改到每秒1次就足够了。

目前是5秒请求一次。

https://github.com/dushixiang/next-terminal/blob/master/web/src/components/dashboard/Monitoring.js#L55
