### ISSUE TITLE
自从连上一次vnc后，如果中途退出了 然后隔一段时间就需要重启目标服务器才能重新连上

### ISSUE THREAD

**Issue by wolfcdd** [dushixiang/next-terminal#326]
自从连上一次vnc后，如果中途退出了 然后隔一段时间就需要重启目标服务器才能重新连上
Version:1.3.5
日志报错：
WebSocket已关闭	{"sessionId": "63a90f5a-11f0-4929-be90-22c25de544c8", "err": "websocket: close 1005 (no status)"}
请问是什么原因呢，如果把vncserver重新启动一次就可以了。

**Comment by deorth-kku** [comment]
你看看是不是guacd还有日志说认证问题的，我的是这样
```
Jan 28 11:14:12 next-terminal guacd[1248]: VNC server supports protocol version 3.3 (viewer 3.8)
Jan 28 11:14:12 next-terminal guacd[1248]: Selected Security Scheme 0
Jan 28 11:14:12 next-terminal guacd[1248]: VNC connection failed: Too many security failures
Jan 28 11:14:12 next-terminal guacd[1248]: Unable to connect to VNC server.
Jan 28 11:14:12 next-terminal guacd[1248]: guacd[1248]: ERROR:#011Unable to connect to VNC server.
Jan 28 11:14:12 next-terminal guacd[1248]: User "@e46d5584-f6a5-4fba-af37-70348a0edcc2" disconnected (0 users remain)
Jan 28 11:14:12 next-terminal guacd[1248]: guacd[1248]: INFO:#011User "@e46d5584-f6a5-4fba-af37-70348a0edcc2" disconnected (0 users remain)
Jan 28 11:14:12 next-terminal guacd[1248]: guacd[1248]: INFO:#011Last user of connection "$6ca55c55-92a4-4319-b545-84f2b099e870" disconnected
Jan 28 11:14:12 next-terminal guacd[1248]: Last user of connection "$6ca55c55-92a4-4319-b545-84f2b099e870" disconnected
Jan 28 11:14:12 next-terminal next-terminal[736]: 2023-01-28 11:14:12.796#011debug#011log/logger.go:125#011WebSocket已关闭#011{"sessionId": "848d0c14-b7b7-4661-81fe-8415f6d5772d", "err": "websocket: close 1005 (no status)"}
```
估计是连通性测试被当成暴力破解密码了。tigervnc的文档也是一团糟，我现在连vncserver的日志都没找到，也不知道怎么关闭max passwd retry

**Comment by blue-duty** [comment]
不要给vnc设置资产状态检测就好了

**Comment by deorth-kku** [comment]
> 不要给vnc设置资产状态检测就好了

@blue-duty 没找着这个配置项呢

**Comment by dushixiang** [comment]
> > 不要给vnc设置资产状态检测就好了
> 
> @blue-duty 没找着这个配置项呢

计划任务里面，默认是全部资产。

**Comment by deorth-kku** [comment]
> > > 不要给vnc设置资产状态检测就好了
> > 
> > 
> > @blue-duty 没找着这个配置项呢
> 
> 计划任务里面，默认是全部资产。

然后资产状态检测-自定义资产选择的时候只有ssh的资产可以选了😂  
![所有资产](https://user-images.githubusercontent.com/23164110/215401009-9f5c61ce-1d70-40b5-b415-d96ca255dae2.png)  
![资产选择](https://user-images.githubusercontent.com/23164110/215401034-222b477d-cb61-4e84-b436-9013776736ac.png)  

btw，我找到了vnc服务端黑名单的配置项，关闭了黑名单之后这个问题不再复现，可以确认是这个原因导致的。  
tigervnc关闭黑名单的方法是：在~/.vnc/config中加入
`UseBlacklist=0`

**Comment by wolfcdd** [comment]
> > > 不要给vnc设置资产状态检测就好了
> > 
> > 
> > @blue-duty 没找着这个配置项呢
> 
> 计划任务里面，默认是全部资产。

已按照这个设置自定义了检测的资产，过两天再跟进确认下。谢谢。

**Comment by wolfcdd** [comment]
> > > > 不要给vnc设置资产状态检测就好了
> > > 
> > > 
> > > @blue-duty 没找着这个配置项呢
> > 
> > 
> > 计划任务里面，默认是全部资产。
> 
> 已按照这个设置自定义了检测的资产，过两天再跟进确认下。谢谢。

经过确认，已经没有这个问题了，可以通过此操作处理。感谢。
