### ISSUE TITLE
通过VNC协议连接Windows，右上角能否增加文件传输功能图标

### ISSUE THREAD

**Issue by sifanx** [dushixiang/next-terminal#331]
![001](https://user-images.githubusercontent.com/42561369/213955616-27dee5e8-4b91-4242-988a-ff1a6556b90a.jpg)

**Comment by sifanx** [comment]
RDP协议是有的，但是VNC协议没有，不太方便
![002](https://user-images.githubusercontent.com/42561369/213955697-db37cc98-f4ed-4bc1-9198-bb2b2710dbc6.jpg)

**Comment by dushixiang** [comment]
> RDP协议是有的，但是VNC协议没有，不太方便
> 
> ![002](https://user-images.githubusercontent.com/42561369/213955697-db37cc98-f4ed-4bc1-9198-bb2b2710dbc6.jpg)
> 
> 

vnc 的标准协议是没有支持文件上传的，因此搞不定。
