### ISSUE TITLE
docker最新社区版RDP无法保存回放

### ISSUE THREAD

**Issue by ggfvictor** [dushixiang/next-terminal#332]
根据报错，检查过路径下的文件夹权限，均正常，但是还是无法保存回放录屏
经过测试，最新企业版没有这个bug

**Comment by dushixiang** [comment]
> 根据报错，检查过路径下的文件夹权限，均正常，但是还是无法保存回放录屏 经过测试，最新企业版没有这个bug

收到，将在下一次更新中修复。
