### ISSUE TITLE
优化改善：tips提醒能否只显示一次或者可以更加友善

### ISSUE THREAD

**Issue by wolfcdd** [dushixiang/next-terminal#334]
这两个提醒 如果选择复制一大段文本 就会不停提示 能否优化呢。
![Snipaste_2023-02-01_09-48-27](https://user-images.githubusercontent.com/5728354/215926039-f11e0879-02b0-44a5-aca6-7e72acd3f3a2.png)
![Snipaste_2023-02-01_09-47-42](https://user-images.githubusercontent.com/5728354/215926049-e43f63f2-6b4a-44d8-93e1-c1f5dad9437a.png)

**Comment by dushixiang** [comment]
> 这两个提醒 如果选择复制一大段文本 就会不停提示 能否优化呢。 ![Snipaste_2023-02-01_09-48-27](https://user-images.githubusercontent.com/5728354/215926039-f11e0879-02b0-44a5-aca6-7e72acd3f3a2.png) ![Snipaste_2023-02-01_09-47-42](https://user-images.githubusercontent.com/5728354/215926049-e43f63f2-6b4a-44d8-93e1-c1f5dad9437a.png)

感谢建议，后续会调整为可关闭不再提示。
