### ISSUE TITLE
【问题反馈】文件上传异常，详见描述

### ISSUE THREAD

**Issue by wolfcdd** [dushixiang/next-terminal#335]
文件上传成功，但是在远程找不到对应的文件，请问是什么地方需要修改配置吗
![image](https://user-images.githubusercontent.com/5728354/216484062-3a1f3dd6-2397-4b02-9b64-e2dc25e9482b.png)

**Comment by dushixiang** [comment]
1.3.7 之后的版本修复了这个问题。
