### ISSUE TITLE
建议“会话审计-历史会话”里增加“名称”、“网络”、“用户名”的搜索功能

### ISSUE THREAD

**Issue by sifanx** [dushixiang/next-terminal#338]
建议“会话审计-历史会话”里增加“名称”、“网络”、“用户名”的搜索功能，因为历史会话一旦多了以后，很难找，要一页一页的去翻了找

**Comment by dushixiang** [comment]
> 建议“会话审计-历史会话”里增加“名称”、“网络”、“用户名”的搜索功能，因为历史会话一旦多了以后，很难找，要一页一页的去翻了找

感谢建议，将在下次更新中增加这些筛选条件。
