### ISSUE TITLE
Oracle的vps，使用私钥无法登录

### ISSUE THREAD

**Issue by la0wei** [dushixiang/next-terminal#341]
![msedge_0JAR1yrq26](https://user-images.githubusercontent.com/3761308/224338502-affc061c-46b4-4e1c-b187-4f21e57860bf.png)

trying to connect to the server ...
创建SSH客户端失败：ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain 
connection is closed.

私钥未加密码。
该私钥可以在https://sshwifty-demo.nirui.org/ 网页上传密钥登录

**Comment by dushixiang** [comment]
> ![msedge_0JAR1yrq26](https://user-images.githubusercontent.com/3761308/224338502-affc061c-46b4-4e1c-b187-4f21e57860bf.png)
> 
> trying to connect to the server ... 创建SSH客户端失败：ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain connection is closed.
> 
> 私钥未加密码。 该私钥可以在https://sshwifty-demo.nirui.org/ 网页上传密钥登录

请问您使用的 ssh 私钥类型是什么？

**Comment by la0wei** [comment]
root@cc:~# ssh-keygen -lf pub.key 
2048 SHA256:s***********************************soIso ssh-key-2022-11-02 (RSA)
命令行验证了公钥，应为rsa 2048
Oracle网站下载，自动生成的

**Comment by xbclub** [comment]
> @dushixiang root@cc:~# ssh-keygen -lf pub.key 2048 SHA256:s***********************************soIso ssh-key-2022-11-02 (RSA) 命令行验证了公钥，应为rsa 2048 Oracle网站下载，自动生成的

我也遇到了相同的问题，再更新golang.org/x/crypto依赖以后自行编译后解决。
```bash
go get -u golang.org/x/crypto
```

**Comment by luckiestone** [comment]
我是docker安装的，遇到了同样的问题。

**Comment by yumusb** [comment]
有可能是密钥类型问题。ubuntu22 以后默认不再支持 rsa 类型的密钥。

echo PubkeyAcceptedKeyTypes=+ssh-rsa >> /etc/ssh/sshd_config
service ssh reload
