### ISSUE TITLE
最新版本使用Nginx反代会打不开

### ISSUE THREAD

**Issue by zhucaidan** [dushixiang/next-terminal#343]
![image](https://user-images.githubusercontent.com/47970938/224642599-2f5a532b-440a-400f-8a44-9c948ada12ce.png)

通过docker compose部署的；尝试清空缓存，重启服务器，开启Cloudlfare开发者模式都不行

直接通过服务器IP+端口可以访问，通过服务器Nginx直连或者Cloudflare的话有两个JS直接404，没更新前是正常的

**Comment by zhucaidan** [comment]
![image](https://user-images.githubusercontent.com/47970938/224647277-904ba24f-240f-469c-9f66-cd71dad13cc2.png)

**Comment by dushixiang** [comment]
> ![image](https://user-images.githubusercontent.com/47970938/224642599-2f5a532b-440a-400f-8a44-9c948ada12ce.png)
> 
> 通过docker compose部署的；尝试清空缓存，重启服务器，开启Cloudlfare开发者模式都不行
> 
> 直接通过服务器IP+端口可以访问，通过服务器Nginx直连或者Cloudflare的话有两个JS直接404，没更新前是正常的

直接通过服务器IP+端口可以访问的话证明系统本身是没问题的，是不是你的nginx配置里面有一些拦截规则呢？

**Comment by zhucaidan** [comment]
用的是宝塔的环境，没有装任何防火墙

反代配置如下：

location / {
    proxy_pass http://127.0.0.1:8088/;
    proxy_set_header Host      $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $http_connection;
}
