### ISSUE TITLE
浏览器在最大化和还原的操作过程中容易导致断连

### ISSUE THREAD

**Issue by MakiseSuki** [dushixiang/next-terminal#346]
Next-Terminal部署在CentOS Linux release 7.5上，使用的最新镜像，看web页面下方，版本大概是1.3.6
客户端这边浏览器是chrome 111.0.5563.111
连接的资产 操作系统同样是CentOS Linux release 7.5，操作流畅，但是发现在浏览器从窗口模式→最大化→窗口模式的操作之后，提示connection is closed.

基本稳定复现

**Comment by xbclub** [comment]
遇到了同样的问题

**Comment by wixb50** [comment]
必现

**Comment by dushixiang** [comment]
> 必现
最新版本 v1.3.9？

**Comment by wixb50** [comment]
对：
Copyright © 2020-2023 dushixiang, All Rights Reserved. Version:1.3.9

远程连接得是win11， 调整浏览器窗口就会断连，包括最大化，全屏
