### ISSUE TITLE
ssh连接报错

### ISSUE THREAD

**Issue by ossplus** [dushixiang/next-terminal#351]
docker方式安装，密钥(无密码)，
创建SSH客户端失败：ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain 
同样的密钥，本地是可以连上服务器的；

看历史问题，有说使用原生ssh？请问怎么设置

**Comment by 4Aiur** [comment]
我用ed25519算法生成的密钥对就是无法登录, 报错 
```
trying to connect to the server ...
创建SSH客户端失败：ssh: no key found 
connection is closed.
```

然后我发现复制私钥时 要把前后的---注释也一起复制了
```
-----BEGIN OPENSSH PRIVATE KEY-----
id_ed25519
-----END OPENSSH PRIVATE KEY-----
```
然后就能正常登录, 你看看是不是和我一样的原因

**Comment by nickfan** [comment]
![image](https://user-images.githubusercontent.com/100613/233772309-604cf297-c578-4495-8c7e-b3ca7ede8722.png)
同样的问题，无法登录

**Comment by luckiestone** [comment]
同样的问题，不知道是不是新的docker镜像移除了模式切换选项？高级设置中只有socks。看了另一条issue，似乎是要更新golang.org/x/crypto，不知具体是哪个原因。

**Comment by yutianhot** [comment]
我也是一样的问题。还未解决

**Comment by nickfan** [comment]
最新的镜像验证修复了。

**Comment by dushixiang** [comment]
> 最新的镜像验证修复了。

感谢反馈，稍后发正式版镜像。

**Comment by luckiestone** [comment]
> > 最新的镜像验证修复了。
> 
> 感谢反馈，稍后发正式版镜像。

我这边仍然没有修复，机器是甲骨文ARM ubuntu 20，key是由puttygen生成的，然后导出到openssh后复制的文本内容。仍然提示相同的错误。
