### ISSUE TITLE
guacamole-server升级到1.5.1的疑问。

### ISSUE THREAD

**Issue by zzyyll2** [dushixiang/next-terminal#361]
你好，
![image](https://github.com/dushixiang/next-terminal/assets/22398806/fd48c7f8-7638-4a56-b42c-601ba3e28569)

我看到guacamole-server这个是你自己打的镜像，镜像里guacamole-server的版本是1.4.0，现在官方已经是1.5.1了，请问我直接下载官方的guacamole-server:1.5.1的能用吗？请问下你重新打包的guacamole-server，有客制化的内容吗？因为我在你的代码库里没有看到guacamole-server这个工程，所以有此疑问，谢谢。
![image](https://github.com/dushixiang/next-terminal/assets/22398806/5dc67f90-06ce-4414-ae79-39f5d5dd0827)

**Comment by dushixiang** [comment]
只是安装了一个字体，因为1.5.x更新导致arm的镜像没办法打包，暂时没时间研究，也就没更新。

**Comment by zzyyll2** [comment]
知道了，谢谢。
