### ISSUE TITLE
优化登陆安全。

### ISSUE THREAD

**Issue by mingyue0094** [dushixiang/next-terminal#365]
现在时，输入账号和密码。错误，则显示用户或者密码错误。正确，则显示二步动态验证。

因此，有风险，能爆破出，正确的用户名和密码。

所以，是否可以，优化为。在有二步验证时，输入账号密码就直接进入输入二步动态验证。

然后，用户名，密码，二部验证全符合，则通过，否则，提示，用户名或密码或动态验证错误。 

这样可以极大的避免，正确的用户名和密码被爆破出来。毕竟，这个登陆页面，是在公网暴露的。

**Comment by dushixiang** [comment]
你给的解决方案是需要在登录前发送一个请求校验【账号】是否开启了二次验证，这样很更加容易爆破出来【账号】，从而进一步爆破密码。

目前的方案我认为还更加安全一点，因为需要【账号】+【密码】全部正确才行。
