### ISSUE TITLE
docker镜像   gucad:1.5.2   rdp 有部分问题 。。。

### ISSUE THREAD

**Issue by mingyue0094** [dushixiang/next-terminal#369]
docker-compose 启动
docker镜像   gucad:1.5.2   rdp 有部分问题

连接win有的正常，有的就提示
https://github.com/dushixiang/next-terminal/issues/228   

之前构建时，用的last默认是 gucad:1.4.0 就正常。然后，修改docker-compose.yml 使用gucad:1.4.0 重新构建启动。就又可以了。

**Comment by dushixiang** [comment]
> 

你有尝试按照 #228 这个 issues 尝试修改权限吗？

**Comment by hyhy01** [comment]
这个镜像我用非root用户用podman运行是正常的。root用户就不行了
