### ISSUE TITLE
我原生安装的，请问guacd日志在那里啊？

### ISSUE THREAD

**Issue by sxcisco** [dushixiang/next-terminal#375]
找了半天没找到guacd日志，
我现在设置rdp登录。连接上服务器就断开，不知道是啥情况；
想看下guacd日志，确不知道在那里，求大佬帮忙一下；

**Comment by dushixiang** [comment]
> 找了半天没找到guacd日志， 我现在设置rdp登录。连接上服务器就断开，不知道是啥情况； 想看下guacd日志，确不知道在那里，求大佬帮忙一下；

`/var/log/messages`

**Comment by sxcisco** [comment]
[](url)> > 找了半天没找到guacd日志， 我现在设置rdp登录。连接上服务器就断开，不知道是啥情况； 想看下guacd日志，确不知道在那里，求大佬帮忙一下；
> 
> `/var/log/messages`

老大，我rdp显示连接成功，然后立马就显示连接关闭，这个是咋回事啊？
![QQ截图20230614123253](https://github.com/dushixiang/next-terminal/assets/21124799/adcf1631-9b5c-4eaa-8651-ea01d9ed4c7e)
![Uploading QQ截图20230614123312.png…]()

**Comment by sxcisco** [comment]
[
![Uploading QQ截图20230614123312.png…]()
](url)

**Comment by sxcisco** [comment]
![Uploading QQ截图20230614123312.png…]()

**Comment by sxcisco** [comment]
Jun 14 00:31:09 quiet-choice-7 next-terminal: 2023-06-14 00:31:09.353#011debug#011log/logger.go:125#011新建 guacd 会话#011{"sessionId": "b6b03bd0-fbfd-4871-bc9e-48b803938741", "addr": "127.0.0.1:4822", "asset": "13.208.249.57:3389"}
Jun 14 00:31:09 quiet-choice-7 guacd[11512]: Creating new client for protocol "rdp"
Jun 14 00:31:09 quiet-choice-7 guacd: guacd[11512]: INFO:#011Creating new client for protocol "rdp"
Jun 14 00:31:09 quiet-choice-7 guacd: guacd[11512]: INFO:#011Connection ID is "$5c6bb71e-b982-4ac6-b75a-7f104ac16144"
Jun 14 00:31:09 quiet-choice-7 guacd[11512]: Connection ID is "$5c6bb71e-b982-4ac6-b75a-7f104ac16144"
Jun 14 00:31:09 quiet-choice-7 guacd[21552]: Security mode: Negotiate (ANY)
Jun 14 00:31:09 quiet-choice-7 next-terminal: 2023-06-14 00:31:09.369#011debug#011log/logger.go:125#011新建会话成功#011{"sessionId": "b6b03bd0-fbfd-4871-bc9e-48b803938741"}
Jun 14 00:31:09 quiet-choice-7 guacd: guacd[21552]: INFO:#011Security mode: Negotiate (ANY)
Jun 14 00:31:09 quiet-choice-7 guacd: guacd[21552]: INFO:#011Resize method: reconnect
Jun 14 00:31:09 quiet-choice-7 guacd: guacd[21552]: INFO:#011No clipboard line-ending normalization specified. Defaulting to preserving the format of all line endings.
Jun 14 00:31:09 quiet-choice-7 guacd: guacd[21552]: INFO:#011User "@77d22e75-15fb-4e60-a3c9-f4f57a37968f" joined connection "$5c6bb71e-b982-4ac6-b75a-7f104ac16144" (1 users now present)
Jun 14 00:31:09 quiet-choice-7 guacd[21552]: Resize method: reconnect
Jun 14 00:31:09 quiet-choice-7 guacd: guacd[21552]: INFO:#011Recording of session will be saved to "/usr/local/next-terminal/data/recording/b6b03bd0-fbfd-4871-bc9e-48b803938741/recording".
Jun 14 00:31:09 quiet-choice-7 guacd[21552]: No clipboard line-ending normalization specified. Defaulting to preserving the format of all line endings.
Jun 14 00:31:09 quiet-choice-7 guacd[21552]: User "@77d22e75-15fb-4e60-a3c9-f4f57a37968f" joined connection "$5c6bb71e-b982-4ac6-b75a-7f104ac16144" (1 users now present)
Jun 14 00:31:09 quiet-choice-7 guacd[21552]: Recording of session will be saved to "/usr/local/next-terminal/data/recording/b6b03bd0-fbfd-4871-bc9e-48b803938741/recording".
Jun 14 00:31:09 quiet-choice-7 guacd[21552]: Loading keymap "base"
Jun 14 00:31:09 quiet-choice-7 guacd: guacd[21552]: INFO:#011Loading keymap "base"
Jun 14 00:31:09 quiet-choice-7 guacd: guacd[21552]: INFO:#011Loading keymap "en-us-qwerty"
Jun 14 00:31:09 quiet-choice-7 guacd[21552]: Loading keymap "en-us-qwerty"
Jun 14 00:31:15 quiet-choice-7 guacd[21552]: Connected to RDPDR 1.13 as client 0x0003
Jun 14 00:31:15 quiet-choice-7 kernel: guacd[21557]: segfault at 0 ip 00007fc3e00bc754 sp 00007fc3dafea718 error 6 in libc-2.17.so[7fc3e0033000+1b6000]
Jun 14 00:31:15 quiet-choice-7 guacd: guacd[21552]: INFO:#011Connected to RDPDR 1.13 as client 0x0003
Jun 14 00:31:15 quiet-choice-7 guacd[11512]: Connection "$5c6bb71e-b982-4ac6-b75a-7f104ac16144" removed.
Jun 14 00:31:15 quiet-choice-7 guacd: guacd[11512]: INFO:#011Connection "$5c6bb71e-b982-4ac6-b75a-7f104ac16144" removed.
Jun 14 00:31:15 quiet-choice-7 next-terminal: 2023-06-14 00:31:15.701#011debug#011log/logger.go:125#011会话关闭#011{"会话ID": "b6b03bd0-fbfd-4871-bc9e-48b803938741", "原因": "远程连接已关闭"}
Jun 14 00:31:16 quiet-choice-7 next-terminal: record not found
Jun 14 00:31:16 quiet-choice-7 next-terminal: 2023-06-14 00:31:16.242#011error#011log/logger.go:137#011api error#011{"err": "record not found"}
Jun 14 00:31:16 quiet-choice-7 next-terminal: next-terminal/server/log.Error
Jun 14 00:31:16 quiet-choice-7 next-terminal: /home/runner/work/next-terminal/next-terminal/server/log/logger.go:137
Jun 14 00:31:16 quiet-choice-7 next-terminal: next-terminal/server/app/middleware.ErrorHandler.func1
Jun 14 00:31:16 quiet-choice-7 next-terminal: /home/runner/work/next-terminal/next-terminal/server/app/middleware/error_handler.go:18
Jun 14 00:31:16 quiet-choice-7 next-terminal: github.com/labstack/echo/v4/middleware.CORSWithConfig.func1.1
Jun 14 00:31:16 quiet-choice-7 next-terminal: /home/runner/go/pkg/mod/github.com/labstack/echo/v4@v4.10.2/middleware/cors.go:264
Jun 14 00:31:16 quiet-choice-7 next-terminal: github.com/labstack/echo/v4/middleware.RecoverWithConfig.func1.1
Jun 14 00:31:16 quiet-choice-7 next-terminal: /home/runner/go/pkg/mod/github.com/labstack/echo/v4@v4.10.2/middleware/recover.go:119
Jun 14 00:31:16 quiet-choice-7 next-terminal: github.com/labstack/echo/v4.(*Echo).ServeHTTP
Jun 14 00:31:16 quiet-choice-7 next-terminal: /home/runner/go/pkg/mod/github.com/labstack/echo/v4@v4.10.2/echo.go:662
Jun 14 00:31:16 quiet-choice-7 next-terminal: net/http.serverHandler.ServeHTTP
Jun 14 00:31:16 quiet-choice-7 next-terminal: /opt/hostedtoolcache/go/1.20.4/x64/src/net/http/server.go:2936
Jun 14 00:31:16 quiet-choice-7 next-terminal: net/http.(*conn).serve
