### ISSUE TITLE
ssh: handshake failed

### ISSUE THREAD

**Issue by ruanun** [dushixiang/next-terminal#385]
ssh连接失败，原生和guacd模式都会出现；

创建SSH客户端失败：ssh: handshake failed: ssh: no common algorithm for host key; client offered: [ssh-rsa-cert-v01@openssh.com ssh-dss-cert-v01@openssh.com ecdsa-sha2-nistp256-cert-v01@openssh.com ecdsa-sha2-nistp384-cert-v01@openssh.com ecdsa-sha2-nistp521-cert-v01@openssh.com ssh-ed25519-cert-v01@openssh.com ecdsa-sha2-nistp256 ecdsa-sha2-nistp384 ecdsa-sha2-nistp521 ssh-rsa ssh-dss ssh-ed25519], server offered: [rsa-sha2-512 rsa-sha2-256]

版本：Next Terminal ©2021 dushixiang Version:1.2.2

**Comment by dushixiang** [comment]
> ssh连接失败，原生和guacd模式都会出现；
> 
> 创建SSH客户端失败：ssh: handshake failed: ssh: no common algorithm for host key; client offered: [[ssh-rsa-cert-v01@openssh.com](mailto:ssh-rsa-cert-v01@openssh.com) [ssh-dss-cert-v01@openssh.com](mailto:ssh-dss-cert-v01@openssh.com) [ecdsa-sha2-nistp256-cert-v01@openssh.com](mailto:ecdsa-sha2-nistp256-cert-v01@openssh.com) [ecdsa-sha2-nistp384-cert-v01@openssh.com](mailto:ecdsa-sha2-nistp384-cert-v01@openssh.com) [ecdsa-sha2-nistp521-cert-v01@openssh.com](mailto:ecdsa-sha2-nistp521-cert-v01@openssh.com) [ssh-ed25519-cert-v01@openssh.com](mailto:ssh-ed25519-cert-v01@openssh.com) ecdsa-sha2-nistp256 ecdsa-sha2-nistp384 ecdsa-sha2-nistp521 ssh-rsa ssh-dss ssh-ed25519], server offered: [rsa-sha2-512 rsa-sha2-256]
> 
> 版本：Next Terminal ©2021 dushixiang Version:1.2.2

更新一下版本吧，旧版本支持的算法比较少。
