### ISSUE TITLE
debian无法运行

### ISSUE THREAD

**Issue by xltzsoft** [dushixiang/next-terminal#39]
debian64 arm版，提示“可执行文件格式错误”
期待编译支持arm版本
主机是树莓派4b

**Comment by dushixiang** [comment]
我手上暂时没有arm的硬件，建议手动编译一下。

**Comment by Jonathon52306** [comment]
> debian64 arm版，提示“可执行文件格式错误”
> 期待编译支持arm版本
> 主机是树莓派4b

这个可以直接golang编译一下
按照这个参数
`go env && CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -a -ldflags '-linkmode external -extldflags "-static"' -o next-terminal main.go`

**Comment by xltzsoft** [comment]
好的，谢谢！
