### ISSUE TITLE
[功能请求]希望能添加形如[通过代理发起连接]的功能

### ISSUE THREAD

**Issue by MasterOfStar** [dushixiang/next-terminal#40]
在国内国外都有机器的话，墙就是个问题了... 有时候无法做到保证都能联通（单向墙 双向墙等情况）
因此请求添加 **通过代理连接** 或类似的功能 保证通联性同时也能起到一定的加速功能。
希望可以对每个资产单独配置一个代理，防止代理起到绕全球减速作用。

**Comment by dushixiang** [comment]
已加入开发计划，打算对ssh和telnet资产进行支持。
