### ISSUE TITLE
proxy連線至自架主機異常，但demo網站正常

### ISSUE THREAD

**Issue by ptoyhawinf** [dushixiang/next-terminal#406]
家裡使用docker安裝，本來在公司使用正常，但在公司使用proxy代理後
可以看到資產列表清單，連線時會出現遠程服務未找到，歷史會話裡也找不到公司ip連線記錄

但在demo網站卻可以成功開啟rdp的主機，也從歷史會話裡找的到公司ip連線的記錄
可以怎麼查修??

**Comment by dushixiang** [comment]
可能是你的反向代理有问题，要支持websocket&nbsp;



发自我的iPhone


------------------ 原始邮件 ------------------
From: ptoyhawinf ***@***.***&gt;
发送时间: 09/20/2023, 14:23
To: dushixiang/next-terminal ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
Subject: Re: [dushixiang/next-terminal] proxy連線至自架主機異常，但demo網站正常 (Issue #406)





 
家裡使用docker安裝，本來在公司使用正常，但在公司使用proxy代理後
 可以看到資產列表清單，連線時會出現遠程服務未找到，歷史會話裡也找不到公司ip連線記錄
 
但在demo網站卻可以成功開啟rdp的主機，也從歷史會話裡找的到公司ip連線的記錄
 可以怎麼查修??

**Comment by ptoyhawinf** [comment]
多謝dushixiang，設定好反向代理後，已排除問題。
