### ISSUE TITLE
希望增加查看服务器状态功能

### ISSUE THREAD

**Issue by auosun** [dushixiang/next-terminal#41]
非常感谢作者大大的辛苦付出，希望可以在面板增加实时查看服务器 cpu使用状态当前网络状态功能
类似于这样：
![Snipaste_2021-01-25_23-30-06](https://user-images.githubusercontent.com/37408960/105726793-6a054d00-5f65-11eb-91cc-0fa2c0673c0c.png)
![Snipaste_2021-01-25_23-34-56](https://user-images.githubusercontent.com/37408960/105727341-f31c8400-5f65-11eb-9f3d-964da2cf85ff.png)

希望未来可以增加能够快速查看服务器状态的功能！非常感谢！

**Comment by dushixiang** [comment]
已加入开发计划。

**Comment by dushixiang** [comment]
1.0 之后的版本已经增加了服务器状态。
![image](https://user-images.githubusercontent.com/17633733/131324726-58f00f25-73c6-435a-9a1b-6b49a70b3025.png)
