### ISSUE TITLE
Docker Version:0.0.8 如何更新到最新的0.1.0呢？会丢失配置吗（ps：希望可以支持设备导入导出、批量编辑功能）

### ISSUE THREAD

**Issue by NBSOD** [dushixiang/next-terminal#43]
按照文档docker 拉的lastest，但是是0.8.0版本，里边的设备无法批量编辑。。。而且用户组好像也没有实际的功能，设备授权的时候没有选择用户组的地方，还是只能单个用户选择

**Comment by dushixiang** [comment]
单词写错了，应该是 latest
```
docker push dushixiang/next-terminal:latest
```

新版用户组功能已经完善了。

**Comment by NBSOD** [comment]
> 单词写错了，应该是 latest
> 
> ```
> docker push dushixiang/next-terminal:latest
> ```
> 
> 新版用户组功能已经完善了。

完美！！！多谢大佬，给同事看了下，都觉得不错呢。
