### ISSUE TITLE
建SSH客户端失败：ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain 

### ISSUE THREAD

**Issue by xiaoyi510** [dushixiang/next-terminal#430]
提示:
建SSH客户端失败：ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain 

配置:
ssh 密码
ssh 授权凭证
都进不去

**Comment by wangweiweiwei** [comment]
> 提示: 建SSH客户端失败：ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain
> 
> 配置: ssh 密码 ssh 授权凭证 都进不去

请问一下解决了吗？我也提示这个~

**Comment by wanglixiang90** [comment]
![image](https://github.com/dushixiang/next-terminal/assets/13639913/338d38a2-09ef-4571-9954-221c434d38bb)
开启 sshd服务后无法正常登录ssh （web/ssh 都不行）
请问下怎么解决这个问题？

**Comment by dushixiang** [comment]
这个错误代表你的密码或者密钥不正确，请仔细检查。

**Comment by HKL-Kevin** [comment]
> 这个错误代表你的密码或者密钥不正确，请仔细检查。

不应该啊，我好几个服务器用 Termius 连都正常，密码也是从 Termius 复制过去就是不行
