### ISSUE TITLE
[Feature Request] 资产 IP 能够解析域名

### ISSUE THREAD

**Issue by liangchenhe55** [dushixiang/next-terminal#45]
部分资产没有固定的公网ip，使用 ddns 服务来动态映射。
因此希望资产 ip 一栏允许填写域名，实时解析出 ip 再来连接（或者测试在线状态）

**Comment by dushixiang** [comment]
目前没有限制，可以填写域名。

**Comment by liangchenhe55** [comment]
@dushixiang 确实可以填写但似乎没有解析。

显示资产不可用，也无法连接。已通过公网测试，防火墙和端口转发没有问题，可以连接。
我填写的格式形如 `ip.xxxxx.cn:xxxx` 不知是否有问题

**Comment by liangchenhe55** [comment]
傻了，域名写错了。抱歉抱歉 Orz...
