### ISSUE TITLE
请问如何设置可以防止SSH掉线呢？

### ISSUE THREAD

**Issue by vicnoah** [dushixiang/next-terminal#454]
我使用容器安装的next-terminal，使用时没隔多久就掉线了。其他软件有连接保持的一些配置项，请问next-terminal需要配置这些吗？
ClientAliveInterval 60
ClientAliveCountMax 300

**Comment by dushixiang** [comment]
> 我使用容器安装的next-terminal，使用时没隔多久就掉线了。其他软件有连接保持的一些配置项，请问next-terminal需要配置这些吗？ ClientAliveInterval 60 ClientAliveCountMax 300

默认是没有做任何限制的，如果你使用了反向代理服务器，需要配置读超时参数。

**Comment by vicnoah** [comment]
> > 我使用容器安装的next-terminal，使用时没隔多久就掉线了。其他软件有连接保持的一些配置项，请问next-terminal需要配置这些吗？ ClientAliveInterval 60 ClientAliveCountMax 300
> 
> 默认是没有做任何限制的，如果你使用了反向代理服务器，需要配置读超时参数。

我再研究研究，确实配了个nginx做反向代理。没多久就会收到connection is closed错误
