### ISSUE TITLE
授权凭证明文问题

### ISSUE THREAD

**Issue by sungmee** [dushixiang/next-terminal#46]
今天试着部署 Next Terminal，体验非常棒，谢谢作者的无私奉献。

部署使用了数据库，浏览数据看到所有授权凭证都是明文储存的，是否可以考虑 Hash 后储存呢，这样多少能提高一点安全性，您觉得呢？

**Comment by dushixiang** [comment]
资产的账号密码hash后存储是不可逆的，这样就没办法使用了。目前正在计划增加一个AES加密授权凭证的功能。

**Comment by AndroidOL** [comment]
> 资产的账号密码hash后存储是不可逆的，这样就没办法使用了。目前正在计划增加一个AES加密授权凭证的功能。

能否先删除页面中显示旧密码的功能，相当于只能设置不能读取之前的旧密码。
