### ISSUE TITLE
管理员控制双因子开关

### ISSUE THREAD

**Issue by fm-xiaomo** [dushixiang/next-terminal#466]
1、在系统设置增加个双因子开关的控制项
     · 如果配置开启了双因子的开关
       用户在新建之后，会默认使用全局的双因子开关。在用户初次登陆时，验证完密码 会跳出双因子的二维码让用户来绑定。
     · 如果全局配置了关闭
       用户密码验证完之后就能登陆
2、在用户管理处，为某一个用户单独开启或者关闭双因子认证
      在用户处设定时，效果会覆盖全局的配置

**Comment by dushixiang** [comment]
> 1、在系统设置增加个双因子开关的控制项 · 如果配置开启了双因子的开关 用户在新建之后，会默认使用全局的双因子开关。在用户初次登陆时，验证完密码 会跳出双因子的二维码让用户来绑定。 · 如果全局配置了关闭 用户密码验证完之后就能登陆 2、在用户管理处，为某一个用户单独开启或者关闭双因子认证 在用户处设定时，效果会覆盖全局的配置

企业版有这些功能。
