### ISSUE TITLE
SSH 无法退格

### ISSUE THREAD

**Issue by ixinshang** [dushixiang/next-terminal#48]
你好，我登录华为交换机出现无法使用退格的情况，测试环境如下：
centos 7.2 
docker
Next Terminal ©2021 dushixiang Version:0.1.0
Next Terminal ©2021 dushixiang Version:0.0.8

测试设备：
# Huawei Versatile Routing Platform Software
# VRP (R) software, Version 8.150 (CE6855HI V200R002C50SPC800)
# Copyright (C) 2012-2017 Huawei Technologies Co., Ltd.
# Patch Version: V200R002SPH013

![image](https://user-images.githubusercontent.com/10056396/105946382-2106e300-60a2-11eb-9fa5-4717f2b6e599.png)

**Comment by dushixiang** [comment]
问题已经确认，计划增加退格键的键位映射功能。

**Comment by dushixiang** [comment]
v0.2.0增加了退格键的映射，针对交换机选择Ctrl-H即可。
