### ISSUE TITLE
[Bug]发现三个bug

### ISSUE THREAD

**Issue by Jonathon52306** [dushixiang/next-terminal#49]
1. 在ssh终端中打开sftp点击上传并选择上传文件后出现 "确认"按键点击无效的情况(动画有展示,无反应)[复现难度:低]
2. 在操作审计-在线会话中若有两个及以上的在线会话,选择任意一个监控后其余画面都会变成一样的(即最开始点击监控的画面)[复现难度:低]
3. 使用docker swarm部署后若有两个及以上的pod则会在登陆时无限闪退(即点击登录后主页一闪而过再次跳回登录界面)
    附上docker swarm启动命令`docker service create --name next-terminal -e SQLITE_FILE="/config/next-terminal.db" --mount type=volume,src=next-terminal,dst=/config --replicas 2 -p 80:8088 dushixiang/next-terminal:latest`
    [复现难度:低]

**Comment by Jonathon52306** [comment]
经过编译并更新后
发现问题2已经解决

**Comment by dushixiang** [comment]
问题1：更换了新的文件管理。
问题3：增加了docker-compose启动方式。
