### ISSUE TITLE
使用Caddy反代，出现"Rejected request from RFC1918 IP to public server address"

### ISSUE THREAD

**Issue by mervynsword** [dushixiang/next-terminal#50]
next-terminal运行环境：Docker
next-terminal运行参数：
```
docker run -d \
  --name next-terminal \
  --restart always dushixiang/next-terminal:latest
```

Caddy v1运行环境：Docker
Caddy配置文件：
```
terminal.example.example {
        tls {
                dns cloudflare
        }

        proxy / 172.18.0.5:8088 {
                transparent
                websocket
                header_upstream -Origin
        }
}
```
之后访问http://terminal.example.example，出现"Rejected request from RFC1918 IP to public server address"错误，访问https://terminal.example.example，则为拒绝连接。

**Comment by dushixiang** [comment]
这个问题和此应用无关，是群晖或者openwrt的配置问题。

**Comment by mervynsword** [comment]
额，今天晚上回家又搞了一下，结果是忘记加端口，抱歉打扰了……

**Comment by GoldenString01** [comment]
> 额，今天晚上回家又搞了一下，结果是忘记加端口，抱歉打扰了……

我最近也是这个问题，看了你回复才发现...，外网访问的时候都加了，内网访问就忘了
