### ISSUE TITLE
关于IPv6支持

### ISSUE THREAD

**Issue by asuna** [dushixiang/next-terminal#52]
使用docker安装next-terminal，已开启host的IPv6，并在docker容器中测试可以成功ping通IPv6资产及www.google.com的ipv6地址，但next-terminal中IPv6资产的状态为“不可用“，是目前还不支持IPv6吗？

![image](https://user-images.githubusercontent.com/1998862/106105350-cf805600-617e-11eb-8203-b180dd4601a3.png)

> root@f946822d0084:/usr/local/next-terminal# ping6 www.google.com
PING www.google.com (2607:f8b0:4001:c18::67): 56 data bytes
64 bytes from 2607:f8b0:4001:c18::67: icmp_seq=0 ttl=104 time=50.834 ms
64 bytes from 2607:f8b0:4001:c18::67: icmp_seq=1 ttl=104 time=49.313 ms
64 bytes from 2607:f8b0:4001:c18::67: icmp_seq=2 ttl=104 time=52.028 ms
^C--- www.google.com ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max/stddev = 49.313/50.725/52.028/1.111 ms

> root@f946822d0084:/usr/local/next-terminal# ssh 2001xxxxxx::1
The authenticity of host '2001:xxxx::1 (2001:xxxx::1)' can't be established.
ECDSA key fingerprint is SHA256:xxxxxxxxxxxxxxxxxxxxxxx.
Are you sure you want to continue connecting (yes/no)?

**Comment by if1y** [comment]
实测在容器 IPv6 网络通畅的情况下，在资产设置中把 IPv6 地址用 `[]` 包裹，可以正常使用

**Comment by dushixiang** [comment]
> 实测在容器 IPv6 网络通畅的情况下，在资产设置中把 IPv6 地址用 `[]` 包裹，可以正常使用

原来如此，我查了一下，根据 [RFC 3986](https://www.ietf.org/rfc/rfc3986.txt)的3.2.2章节描述，为了区分端口，所以要用`[]`把IPv6地址包裹起来。

**Comment by if1y** [comment]
> > 实测在容器 IPv6 网络通畅的情况下，在资产设置中把 IPv6 地址用 `[]` 包裹，可以正常使用
> 
> 原来如此，我查了一下，根据 [RFC 3986](https://www.ietf.org/rfc/rfc3986.txt)的3.2.2章节描述，为了区分端口，所以要用`[]`把IPv6地址包裹起来。

可以在这个框里加个判断，区分v4和v6，如果是v6就把用户录入值包裹上 `[]`。
当然手动包裹也不是不能用，只是这样子用户体验会更好一点点。

**Comment by liudicy** [comment]
设置为ipv4，设备能正常接入，但是状态显示不可用是什么问题？

**Comment by dushixiang** [comment]
> 设置为ipv4，设备能正常接入，但是状态显示不可用是什么问题？

目前是定时检查状态的，在“计划任务”中可以看到。
