### ISSUE TITLE
切換授權使用者登錄後，進入資產列表後會有錯誤

### ISSUE THREAD

**Issue by eRicla** [dushixiang/next-terminal#53]
利用Docker Hub拉取建置環境，新增使用者並給予部分連線的資產列表，但進入後會出現「RIGHT and FULL OUTER JOINs are not currently supported」，請問這是設定上有錯誤還是系統有問題?

**Comment by dushixiang** [comment]
sqlite模式多用户时存在问题。

**Comment by czpwpq** [comment]
嗯，我也遇到这个问题了
