### ISSUE TITLE
https支持

### ISSUE THREAD

**Issue by NonCheng** [dushixiang/next-terminal#56]
浏览器到next-terminal这一段是http的
请问有考虑加入https支持吗
demo上也是有https的
谢谢

**Comment by dushixiang** [comment]
下个版本增加https支持。

**Comment by toyqiu** [comment]
> 下个版本增加https支持。

在局域网用n-t访问都没问题，但用群晖的反向代理工具转到https，再用n-t访问所有资产全都访问不成功，也是因为不支持的缘故吗

**Comment by dushixiang** [comment]
> > 下个版本增加https支持。
> 
> 在局域网用n-t访问都没问题，但用群晖的反向代理工具转到https，再用n-t访问所有资产全都访问不成功，也是因为不支持的缘故吗

请参考FAQ里面的第一条，要针对websocket进行特殊的配置。

**Comment by toyqiu** [comment]
> > > 下个版本增加https支持。
> > 
> > 
> > 在局域网用n-t访问都没问题，但用群晖的反向代理工具转到https，再用n-t访问所有资产全都访问不成功，也是因为不支持的缘故吗
> 
> 请参考FAQ里面的第一条，要针对websocket进行特殊的配置。

OK
搞定了，从来没用过群晖反代的websocket配置，长见识了


另外请教，动态指令要怎么用来登陆需要输入密码的root
我分两行写了
sudo -i
pwd
然后还是一直停在password:

**Comment by dushixiang** [comment]
> > > > 下个版本增加https支持。
> > > 
> > > 
> > > 在局域网用n-t访问都没问题，但用群晖的反向代理工具转到https，再用n-t访问所有资产全都访问不成功，也是因为不支持的缘故吗
> > 
> > 
> > 请参考FAQ里面的第一条，要针对websocket进行特殊的配置。
> 
> OK
> 搞定了，从来没用过群晖反代的websocket配置，长见识了
> 
> 另外请教，动态指令要怎么用来登陆需要输入密码的root
> 我分两行写了
> sudo -i
> pwd
> 然后还是一直停在password:

不支持交互式的脚本
