### ISSUE TITLE
不支持ED25519密钥

### ISSUE THREAD

**Issue by snowie2000** [dushixiang/next-terminal#58]
只有RSA密钥可以正常登录，任何ED25519密钥都会登录失败。

**Comment by naiba** [comment]
https://github.com/apache/guacamole-server/blob/4a38d39694bfd6e17f081b6b7c06eeabb1a5c36e/Dockerfile#L65
https://packages.debian.org/jessie/libssh2-1-dev
https://www.libssh2.org/changes.html

@dushixiang 感觉可能通过确保 guacd 编译新 libssh 的简单方式解决问题 `docker build --no-cache=true` ?

**Comment by naiba** [comment]
毕竟 guacd 不支持 「ED25519」 这件事更难接受一点

**Comment by snowie2000** [comment]
根据这个issue https://github.com/oznu/docker-guacamole/issues/50 来看，似乎很难，但是RSA真的已经老了……

**Comment by dushixiang** [comment]
目前正在进行xterm.js+golang ssh的开发，之后ssh不再使用guacamole，密钥问题将在下个版本修复。

**Comment by snowie2000** [comment]
对哦，golang自己有很不错的ssh client库，没有必要用第三方的。

**Comment by naiba** [comment]
> https://github.com/apache/guacamole-server/blob/4a38d39694bfd6e17f081b6b7c06eeabb1a5c36e/Dockerfile#L65
> https://packages.debian.org/jessie/libssh2-1-dev
> https://www.libssh2.org/changes.html
> 
> @dushixiang 感觉可能通过确保 guacd 编译新 libssh 的简单方式解决问题 ~`docker build --no-cache=true`~ / 更新到 `1.3` ?

前天晚上测试了不可行，不需要尝试了，根据这里来看

http://apache-guacamole-general-user-mailing-list.2363388.n4.nabble.com/Libssh2-has-less-key-exchange-methods-when-compare-to-libssh-td8128.html

短期不需要对 guacamole 的 SSH 寄以希望了
