### ISSUE TITLE
关于二次验证和快捷键

### ISSUE THREAD

**Issue by ixinshang** [dushixiang/next-terminal#59]
你好，目前没有强制启用二次验证。
在管理员新增用户时，可否强制指定用户第一次登录后，就强制增加二次验证。

另外，有些快捷键对部分设备可能会有问题，为了防止误操作，可否设置粘贴板、发送快捷按键的开关，全局禁用或者是新增设备时，对指定设备禁用。
![image](https://user-images.githubusercontent.com/10056396/106928299-f4d70c00-670a-11eb-84c1-67850f0b2024.png)
@dushixiang

**Comment by dushixiang** [comment]
二次认证不是必须的，有些内网环境比较安全。
关于剪贴板文件管理等功能目前正在修改中，计划在添加资产时配置是否能够使用这些功能。

**Comment by lihaixin** [comment]
可否在windows主机制定文件夹用于共享，这样不同人上传的文件互相不干扰，另外目前从主机复制文件到文件管理器不成功
@dushixiang

**Comment by dushixiang** [comment]
> 可否在windows主机制定文件夹用于共享，这样不同人上传的文件互相不干扰，另外目前从主机复制文件到文件管理器不成功
> @dushixiang

1.0.0 之后的版本增加了远程桌面文件夹隔离。
