### ISSUE TITLE
关于域中RDP发起连接

### ISSUE THREAD

**Issue by czpwpq** [dushixiang/next-terminal#61]
安装使用过程中发现如果是在企业域中想用域账户管理员对服务器发起RDP连接都是失败的
不知道后续是否能加入域功能

**Comment by dushixiang** [comment]
没有接触过这方便的知识，我查了一下连接时用户名要使用 user@domain.com 这样的格式。

**Comment by czpwpq** [comment]
测试过了。的确这个才是正确的格式，非常感谢大大的回复
