### ISSUE TITLE
关于文件互传的bug

### ISSUE THREAD

**Issue by ulpyuxa** [dushixiang/next-terminal#63]
![Snipaste_2021-02-17_17-36-42](https://user-images.githubusercontent.com/16745176/108186223-14792600-7148-11eb-960f-8448a5760366.jpg)

你好，最近在使用您的项目，真的很好用，免去了密码管理的问题。
但是最近在使用文件互传时遇到个问题。如图所述，下载后的文件名被重新命名为download了，而不是rdp系统里面的文件名称。
期待能将这个bug给解决掉。使用系统里面已经命名好的名称。

**Comment by dushixiang** [comment]
问题已确认，将在下个版本进行修复。
