### ISSUE TITLE
关于一些优化的建议

### ISSUE THREAD

**Issue by Mark-1215** [dushixiang/next-terminal#64]
1、资产列表的每页多少条显示，建议可以在设置中固定。(这样设备多的就不需要每次进去点右下角的每页多少设备了)
2、资产列表，创建时间可以利用友好格式，例如 几小时前，几天前，几月前，几年前，鼠标经过飘窗显示精确时间（与资产名称类似）
3、资产列表，状态可以只显示状态图就行，关于状态图的说明可以写在列表底部或者鼠标经过给与飘窗提示(目的是减少列表臃肿，看上去更加清爽)
4、资产列表，连接协议的颜色和样式可以改一下，这样红蓝会造成跟状态红蓝产生错觉，比如有时候会感觉rdp红色是非正常状态。
5、资产列表，经过上面调整应该有很多空间了，建议把标签栏目加上去。
6、之前版本的资产列表有个IP显示功能，可以利用鼠标经过飘窗在连接协议上展现会更好一些。
效果图
[![y4B74g.md.png](https://s3.ax1x.com/2021/02/20/y4B74g.md.png)](https://imgchr.com/i/y4B74g)
最后说一下这是一个非常棒的项目，感谢。

**Comment by dushixiang** [comment]
部分建议已采纳，v0.2.5版本。
