### ISSUE TITLE
使用原生安装方式安装后，无法查看在线会话和历史会话

### ISSUE THREAD

**Issue by jeahoonchen** [dushixiang/next-terminal#65]
使用原生安装方式安装后，无法查看在线会话和历史会话，这两个页面均为空白，设置的 录屏 是打开的
但是/next-terminal/recording 下存在文件

**Comment by dushixiang** [comment]
请问使用的版本是最新的吗？v0.2.4

**Comment by dushixiang** [comment]
无法复现此问题。

**Comment by zxp** [comment]
我也出现此现象，无论是原生安装还是docker运行都无法查看在线和历史会话，我简单分析了一下mysql日志，发现连接到服务器后sessions表里面记录了当前到会话，但是会话status是connecting，而正常情况应是connected，浏览器console中记录了错误信息，感觉是这个错误阻止了后面设置status为connected到操作。

![image](https://user-images.githubusercontent.com/869234/109740332-1346ff00-7c06-11eb-8a26-e3fb06666172.png)

**Comment by zxp** [comment]
> 我也出现此现象，无论是原生安装还是docker运行都无法查看在线和历史会话，我简单分析了一下mysql日志，发现连接到服务器后sessions表里面记录了当前到会话，但是会话status是connecting，而正常情况应是connected，浏览器console中记录了错误信息，感觉是这个错误阻止了后面设置status为connected到操作。
> 
> ![image](https://user-images.githubusercontent.com/869234/109740332-1346ff00-7c06-11eb-8a26-e3fb06666172.png)

我另一台服务器上使用同样的docker-compose.yml部署的却运行正常，浏览器也没有报错，真是奇怪。

**Comment by dushixiang** [comment]
请问一下版本号是多少？另外强制刷新浏览器有试过吗？

**Comment by zxp** [comment]
v0.2.6 和 v0.2.7都是这样

**Comment by dushixiang** [comment]
问题已经确认，误调用了获取获取麦克风的权限，下个版本将进行修复。

**Comment by phpnbw** [comment]
请问Bug何时修复，我现在 无法查看在线和历史会话，明明有连接着在，在线和历史会话两个都是空的数据

**Comment by dushixiang** [comment]
> 请问Bug何时修复，我现在 无法查看在线和历史会话，明明有连接着在，在线和历史会话两个都是空的数据

本周末。

**Comment by zxp** [comment]
设置通过域名连接是可以查看的，通过IP连接到next-terminal浏览器站点设置里针对麦克风到权限是禁止的，通过域名连接就是允许的了，这样浏览器不会报错，会话状态就会正常保存到数据库中了。
