### ISSUE TITLE
Ubuntu系统RDP不能正常显示

### ISSUE THREAD

**Issue by zzk114043** [dushixiang/next-terminal#66]
体验部署了Next-Terminal，设置简洁好上手，感觉非常好！

但是Docker部署了0.2.5版本，Ubuntu系统RDP远程面似乎无法正常显示，灰屏状态；部署0.0.8版本是可以正常显示连接的。

**Comment by dushixiang** [comment]
能否贴一下后台日志和前端控制台错误输出。我这边测试正常，可以去演示站点体验一下。

**Comment by zzk114043** [comment]
演示站点体验过了，效果很好。我这边0.2.5版本win10 RDP正常连接，Ubuntu RDP好像有问题。
1、资产列表配置相同，Ubuntu18.04server系统RDP连接
![资产列表](https://user-images.githubusercontent.com/60663499/108613308-8c3a9f80-742b-11eb-91dc-1858dd061d22.png)
2、0.0.8版本连接正常
![0 08正常](https://user-images.githubusercontent.com/60663499/108613323-b5f3c680-742b-11eb-9253-062448a861fa.png)
3、0.2.5版本显示连接成功，但灰屏无法加载桌面
![灰屏](https://user-images.githubusercontent.com/60663499/108613339-f18e9080-742b-11eb-91cc-d63233e56832.png)
4、0.2.5版本docker运行日志
![docker日志](https://user-images.githubusercontent.com/60663499/108613360-2b5f9700-742c-11eb-90e7-9adeb99cd9ee.png)
5、usr/local/next-terminal/next-terminal.log日志
![terminal日志](https://user-images.githubusercontent.com/60663499/108613400-9e690d80-742c-11eb-89dc-f8526c41498d.png)

**Comment by dushixiang** [comment]
v0.2.7 修复了这个问题
