### ISSUE TITLE
[Feature Request] 使会话详情的路径栏可写

### ISSUE THREAD

**Issue by if1y** [dushixiang/next-terminal#69]
不知道描述是否清楚。

接入资产后（即连上 SSH/RDP 后），可以通过点击右上角的图标打开一个【会话详情】页面，用以管理机器的文件，这里有个路径展示位：
![image](https://user-images.githubusercontent.com/32222791/108687856-2d138280-7532-11eb-82fc-ec4885d74d51.png)

希望这个路径可以变成一个文本框，通过修改文本框+回车，快速跳转所需的目录~

**Comment by dushixiang** [comment]
感谢建议，将在下个版本进行完善。

**Comment by dushixiang** [comment]
v0.2.7 完成了这个需求。
