### ISSUE TITLE
[bug]telnet强制需要账号密码

### ISSUE THREAD

**Issue by MasterOfStar** [dushixiang/next-terminal#7]
形如```telnet towel.blinkenlights.nl```这种情况无需账户密码的情况下仍强制要求账户密码
![image](https://user-images.githubusercontent.com/21274896/103168762-f0e4de00-4870-11eb-840b-acbcafbc6183.png)

**Comment by dushixiang** [comment]
0.0.2版本修复了这个问题，建议更新。新版本docker安装方式做了调整，现在使用更简单。
