### ISSUE TITLE
使用guacd接入ssh时，第一个按键被忽略

### ISSUE THREAD

**Issue by snowie2000** [dushixiang/next-terminal#70]
如题，连接到ssh后按下的第一个输入会被忽略掉，没有任何反映。

例如连接到1.1.1.1后，输入ps，只显示s，之后的命令都正常。
使用原生接入则没有问题。

**Comment by dushixiang** [comment]
问题已确认，将在下个版本进行修复。

**Comment by dushixiang** [comment]
v0.2.7 修复了这个问题
