### ISSUE TITLE
配合Guacamole 1.3.0注销远程桌面后重连黑屏，无法加载资源管理器

### ISSUE THREAD

**Issue by aheig** [dushixiang/next-terminal#71]
配合Guacamole 1.3.0注销远程桌面（Server 2019）后重连黑屏，无法加载资源管理器
解决办法：通过发送键值Ctrl+Alt+Del，打开“任务管理器”，再打开资源管理器。或者win+x命令终端打开资源管理器。希望作者看到我的反馈的话解决一下这个bug。谢谢！

**Comment by sifanx** [comment]
我用的Guacamole 1.2.0，远程到Windows Server 2019 没问题

**Comment by aheig** [comment]
> 我用的Guacamole 1.2.0，远程到Windows Server 2019没问题

所以可能是Guacamole 1.3.0的锅？
