### ISSUE TITLE
使用vnc连接双屏电脑时，显示不全问题

### ISSUE THREAD

**Issue by fghwett** [dushixiang/next-terminal#72]
网页所在电脑是1920*1080，浏览器chrome，用VNC连接到的电脑为双1080p的屏幕，网页端只能勉强显示一个屏幕的内容，且无法调节

**Comment by fghwett** [comment]
可以通过左右滑动查看两个屏幕的内容，或者进行缩放

**Comment by dushixiang** [comment]
不支持双屏操作。
