### ISSUE TITLE
请问 config.yml 在哪个路径？

### ISSUE THREAD

**Issue by sifanx** [dushixiang/next-terminal#74]
安装说明上说  修改配置文件config.yml
请问 config.yml 在哪个路径？

**Comment by dushixiang** [comment]
1. /etc/next-terminal/config.yml
2. 当前目录

**Comment by sifanx** [comment]
> 1. /etc/next-terminal/config.yml
> 2. 当前目录

cd /etc/next-terminal
提示  -bash: cd: /etc/next-terminal: No such file or directory
那我是不是可以手动创建一个目录 /etc/next-terminal，然后在里面创建一个config.yml进行填充内容？

**Comment by sifanx** [comment]
> /etc 下面的需要自己手动创建，建议在当前目录配置即可。

好的，谢谢，那我在 /root/next-terminal/next-terminal 里创建config.yml试试

**Comment by sifanx** [comment]
页面成功可以打开访问了，这个是不是就是传说中的堡垒机？
