### ISSUE TITLE
rdp 字体平滑有bug

### ISSUE THREAD

**Issue by ColinZeb** [dushixiang/next-terminal#8]
默认没开启，开启之后刷新rdp接口之后生效了，但是一滚动就糊了，点击其他窗口后糊的窗口会恢复平滑，还没发现其他恢复方法。
问题挺简单的我就不截图了。
客户端时chrome，服务器是windows server 2016.

**Comment by dushixiang** [comment]
我在win10上测试的时候没有发现这个问题，你还有测试过其他的win吗？

**Comment by ColinZeb** [comment]
windows server 2012 r2 同样的问题。
然后我试了windows server 2019 提示‘正在等待服务器响应’，不知道是不是兼容性问题。
另外补充个安全性问题，无论是rdp还是ssh需要提示用户确认安全密钥。否则有安全隐患容易被中间人获取密码

**Comment by ColinZeb** [comment]
再补充：回访的时候字体没有糊。

**Comment by ColinZeb** [comment]
最新发现:SSH也会糊，看来只是前端渲染的bug。
浏览器测试了Chrome和Firefox最新版本。Firefox正常，RDP和SSH都没有糊掉。Chrome正常模式和隐身模式都会糊。

**Comment by dushixiang** [comment]
可以补一个图吗？我这边测试没有发现这样的问题。

**Comment by ColinZeb** [comment]
RDP-糊：<img width="785" alt="nt-bug2" src="https://user-images.githubusercontent.com/23497759/103261096-24437c00-49db-11eb-9520-3e9fc944b8f5.png">
RDP-不糊：
<img width="798" alt="nt-bug2-f" src="https://user-images.githubusercontent.com/23497759/103261100-27d70300-49db-11eb-8d76-ed9660a79b0d.png">
SSH-糊：
<img width="1266" alt="nt-bug1" src="https://user-images.githubusercontent.com/23497759/103261102-29a0c680-49db-11eb-821b-7e3c4cee4bf8.png">
SSH-糊：
<img width="1209" alt="nt-bug1-f" src="https://user-images.githubusercontent.com/23497759/103261105-2ad1f380-49db-11eb-9519-e30bd4e42ed0.png">

rdp里点击其他窗口就会不糊，点击宿主机窗口也会不糊，比如截图后就不糊了。
ssh是换行后就不糊，点击宿主机窗口也会不糊，感觉就是个刷新问题。
另外我这显示器分辨率是3840*2160，150%缩放，宿主机系统Win10 20H2
