### ISSUE TITLE
为何点击全屏，或者从全屏模式，按ESC；桌面会自动注销用户

### ISSUE THREAD

**Issue by huanghairong1106** [dushixiang/next-terminal#80]

**Comment by dushixiang** [comment]
无法复现这个问题，当浏览器窗口变化时只会动态调整会话窗口大小。

**Comment by huanghairong1106** [comment]
[record.zip](https://github.com/dushixiang/next-terminal/files/6048189/record.zip)
以上是录频的画面

**Comment by huanghairong1106** [comment]
连接所有的windows不同版本的主机 都这样

**Comment by huanghairong1106** [comment]
除了全屏后,自动注销 ; 然后 无论在 非全屏还是全屏情况下, 基本键盘不能录入信息

**Comment by dushixiang** [comment]
原因应该是你没有录入账号密码进行自动登录导致的

**Comment by huanghairong1106** [comment]
谢谢 已经解决 非常感谢; 如果 我公司有软件的开发需求, 你这边可以合作吗?

发送自 Windows 10 版邮件应用

发件人: dushixiang
发送时间: 2021年2月26日 16:12
收件人: dushixiang/next-terminal
抄送: huanghairong1106; Author
主题: Re:_[dushixiang/next-terminal]_为何点击全屏，或者从全屏模式，按ESC；桌面会自动注销用户_(#80)

原因应该是你没有录入账号密码进行自动登录导致的

**Comment by dushixiang** [comment]
> 谢谢 已经解决 非常感谢; 如果 我公司有软件的开发需求, 你这边可以合作吗? 发送自 Windows 10 版邮件应用 发件人: dushixiang 发送时间: 2021年2月26日 16:12 收件人: dushixiang/next-terminal 抄送: huanghairong1106; Author 主题: Re:_[dushixiang/next-terminal]_为何点击全屏，或者从全屏模式，按ESC；桌面会自动注销用户_(#80) 原因应该是你没有录入账号密码进行自动登录导致的 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

可以的。
