### ISSUE TITLE
是否会添加类似安全入口的访问方式？

### ISSUE THREAD

**Issue by MeowCold** [dushixiang/next-terminal#82]
![0226172933](https://user-images.githubusercontent.com/7279597/109282301-5006a500-7858-11eb-99c5-6292eba0589e.png)

**Comment by dushixiang** [comment]
暂时不会，请不要暴露在互联网中使用，以及开启TOTP认证。

**Comment by MeowCold** [comment]
233 
感觉
https://next-terminal.typesafe.cn/5Rb3iWIcO/#/login
https://223.5.5.5:29653/5Rb3iWIcO/#/login
做为可选项会好些，终究很多人其实也是挂在服务器上做远程访问用。
感觉next-terminal真好用。

**Comment by dushixiang** [comment]
感谢夸奖，安全入口这个功能好像只有宝塔面板有。

**Comment by MeowCold** [comment]
我觉得这估计是有原因得，因为一开始也没有。
大部分人似乎安装面板后都采取的默认的
http://223.5.5.5:8888
后期似乎有人专门针对宝塔扫
建议改端口
但似乎好像好多人都懒得改
再过了一段时间我发现就变成了这样了
另外，好像给面板加https的更少。变相搞的问题变得更多，似乎也出现过被黑问题。
反正最终用户遇到问题找得肯定是宝塔，被黑肯定是你们安全做的烂吧！
我之前就搜宝塔教程就看到有人博客写怎么提权进后台，当时还没安全入口这种方案。

**Comment by dushixiang** [comment]
目前next-terminal连续登录失败5次就会锁定账户5分钟，TOTP验证码是一个6位的数字，我认为在开启TOTP之后想要通过暴力破解的方式登录系统还是比较困难的。
