### ISSUE TITLE
VNC无法远程

### ISSUE THREAD

**Issue by sifanx** [dushixiang/next-terminal#83]
你好，我在服务器上安装了 VNC-Server-6.7.2-Windows.exe ，参数使用的VNC Password进行连接，在资产列表里添加vnc接入协议，授权用户为空，填入授权密码，保存点击 接入 操作，提示“认证失败”，是什么原因？我确定密码没有输入错误的，我用 VNC Viewer是可以正常连接的。
![image](https://user-images.githubusercontent.com/42561369/109443639-02678380-7a76-11eb-9025-634401c52162.png)

**Comment by dushixiang** [comment]
VNC Viewer和 VNC Server是同一家公司的产品，针对VNC协议做了修改，认证的时候增加了密码加密，标准VNC协议是不支持密码加密的。
因此需要在配置VNC Server的时候Encryption选择Prefer on，Authentication选择VNC password。

**Comment by sifanx** [comment]
Encryption改成Prefer on后可以了，非常感谢~
