### ISSUE TITLE
希望增加资产分组功能0.0

### ISSUE THREAD

**Issue by kenser** [dushixiang/next-terminal#85]
使用了一下next-terminal很棒，在使用过程中发现一个问题，服务器数量太多的时候没法按业务分组查看，批量命令执行的时候只能挨个点击。希望可以加入分组的概念，资产可以切换分组显示和查看，批量命令可以选择分组执行。

**Comment by dushixiang** [comment]
分组功能目前是用tag标签方式进行查看的，批量执行命令选择机器的页面正在修改。

**Comment by kenser** [comment]
老大，这个功能啥时候更新鸭
