### ISSUE TITLE
0.2.7版本下rdp/ssh都连不上了

### ISSUE THREAD

**Issue by awardglobal** [dushixiang/next-terminal#89]
连接的时候一直在等待服务器响应。本机直接rdp/ssh没有问题。

**Comment by dushixiang** [comment]
如果使用了nginx反向代理，请参考FAQ里面的配置。
此外请确认一下guacd的进程是否还在。

**Comment by awardglobal** [comment]
> 
> 
> 如果使用了nginx反向代理，请参考FAQ里面的配置。
> 此外请确认一下guacd的进程是否还在。

没有使用反向代理，就是默认的8088端口
guacd进程在的
我使用docker部署的，测试了一下发现是这个问题：
volumes:
      - /root/next-terminal/drive:/usr/local/next-terminal/drive
      - /root/next-terminal/recording:/usr/local/next-terminal/recording
主机下这两个文件夹权限不够造成的，不映射或者文件夹权限足够的时候都能正常
