### ISSUE TITLE
希望能增加谷歌二步验证，谢谢。

### ISSUE THREAD

**Issue by 99969** [dushixiang/next-terminal#9]
如题，希望开发者能增加谷歌二步验证增加安全性。还有就是vnc模式下，在使用vmware自带的vnc无法连接，vmware自带vnc无用户名，且无法设置，希望开发者帮忙做个兼容该类vnc联系，谢谢，顺颂商祺。

**Comment by dushixiang** [comment]
经过测试vmware自带vnc正常可用，谷歌二步验证已加入排期计划。
