### ISSUE TITLE
docker安装的，watchtower自动更新了，怎么我的配置文件都没了？

### ISSUE THREAD

**Issue by phpnbw** [dushixiang/next-terminal#90]
好好的突然输入密码登不上去，显示密码错误，最后尝试了原始密码，登上去发现配置都没了。。。就等于新安装一样，我的配置文件呢。。。用的sqlite方式安装的。自动更新的容器，我看有写备份next-terminal.db。但是这个自动更新，我都没来得及备份。。。

**Comment by dushixiang** [comment]
修改了docker安装文档，增加了sqlite模式启动时的目录映射参数。
