### ISSUE TITLE
关于guacamole的几个问题

### ISSUE THREAD

**Issue by wideweide** [dushixiang/next-terminal#92]
### 1. enable-websocket: false
配置文件【guacamole.properties】增加上面配置使得支持仅通过http协议（不需要websocket）即可实现ssh、rdp等远程访问操作，next-terminal可否做此配置？
 **_强烈建议next-terminal支持此选项_** 
### 2. ssh访问centos乱码
测试过程是这样的：
* 测试对象centos7/8
* 使用xshell等远程工具连接过去不乱码
* 在本地接显示器发现就无法正常显示，最终发现执行zhcon可以进入中文控制台
* guacamole使用docker部署时候ssh远程连接到centos中文乱码，执行zhcon会被视为x-window而终止
* 使用next-terminal通过ssh连接centos，顺滑无乱码 :+1: 
 **_求指点，如何设置使得guacamole中也可以无乱码？_**

**Comment by dushixiang** [comment]
1. 使用http协议会有明显卡顿，故不支持。
2. guacamole需要安装中文字体才能显示中文，也就是guacd服务所在机器。

**Comment by wideweide** [comment]
> 1. 使用http协议会有明显卡顿，故不支持。
> 2. guacamole需要安装中文字体才能显示中文，也就是guacd服务所在机器。

明显卡顿也比没有强啊，求支持，至少最为一个可选项
有些场景不允许走ws协议但http可以

**Comment by dushixiang** [comment]
暂时无此类开发计划。

**Comment by wideweide** [comment]
继续请教一下，我用宽带网络模拟部署了guacamole（enable-websocket: false），并在阿里云主机上用nginx做了反向代理，之后在在firefox中禁用ws（network.websocket.max-connections = 0），是**可以远程连接服务器并操作的，效果还能接受，没有明显卡顿**

但是在实际网络部署的时候，路由器/光闸设备禁用ws的情况，连接的时候有报错： http tunnel ... read operation ... error

求指点迷津可能是什么原因造成的？
另哪个guacamole的社区比较活跃？

**Comment by dushixiang** [comment]
在使用ssh协议时，按住enter键快速刷屏或者安装软件时即可看出明显区别。
我未使用http协议的guacamole，无法回答你的问题。
guacamole社区我不太了解，查看官方文档或者jira即可。
