### ISSUE TITLE
请问0.2.7版如何升级到0.3.2?

### ISSUE THREAD

**Issue by sifanx** [dushixiang/next-terminal#93]
今天访问github发现软件有新的版本了，请问如何升级呢？

**Comment by dushixiang** [comment]
docker安装的参考 FAQ https://github.com/dushixiang/next-terminal/blob/master/docs/faq.md
原生安装的替换二进制文件`next-terminal`和 `web`文件夹

**Comment by sifanx** [comment]
好的，谢谢，我是原生安装的，那我替换一下
