### ISSUE TITLE
能否增加批量导入资产的功能？

### ISSUE THREAD

**Issue by sifanx** [dushixiang/next-terminal#94]
你好，我们单位电脑有几百台左右，我们目前是用radmin远程的，科室有多个人共同维护，在维护radmin资产列表很不方便，很难共享使用，所以想通过next-terminal用VNC远程连接看看，VNC密码统一的，用的授权凭证添加资产，但是前期录入资产信息是个麻烦事，需要一台台录入，能否后期增加功能，导入excel文件进行批量导入资产与用户授权？

**Comment by dushixiang** [comment]
目前正在开发导入CSV格式资产，计划本周五更新。

**Comment by sifanx** [comment]
好的，谢谢，刚又发现一个事情，在增加资产的时候，授权人数要一个个添加进去，我们科室有十几个人，每增加一个资产，都要点授权人数，把十几个人加进去，有点麻烦，能否在授权人数里可以添加用户组，这样每次添加资产的时候我只要选这个用户组就可以了，而且科室有新成员增加的话，我只要在用户组里把这新人加进去，那他就直接可以远程所有资产了，不用再在资产里去添加新用户授权了

**Comment by dushixiang** [comment]
可以从用户组这里进行资产分配

**Comment by sifanx** [comment]
> 可以从用户组这里进行资产分配

用户组是对现有的资产进行分配，如果是新增资产， 那就只能在资产添加那里进行用户授权，如果我用户有100个，意味着在授权人数的时候要点100次，如果能选用户组的话，我只要点1次就可以了，就能节省很多时间了，这样感觉也合理一些。

不过现在想想，在新增资产以后，我先不授权人数，直接到用户组里去进行授权资产也可以，这样只要把新增的资产添加进去就行了，谢谢解惑。
