### ISSUE TITLE
win rdp模式不支持‘域’认证

### ISSUE THREAD

**Issue by abcdelf** [dushixiang/next-terminal#96]
next terminal的配置
[
<img width="566" alt="截屏2021-03-10 下午9 58 53" src="https://user-images.githubusercontent.com/13900206/110674998-68d66980-820d-11eb-9386-8d45993d6320.png">
](url)

原生gam的配置项：
<img width="370" alt="截屏2021-03-10 下午10 01 07" src="https://user-images.githubusercontent.com/13900206/110675348-bce14e00-820d-11eb-86b4-84496b4e8af7.png">

希望能够过加入win的‘域’认证支持

**Comment by dushixiang** [comment]
下个版本会增加此功能。

**Comment by dushixiang** [comment]
v0.3.3 增加了此功能。
