### ISSUE TITLE
能否访问服务器所在内网的其他服务器？

### ISSUE THREAD

**Issue by z1073** [dushixiang/next-terminal#99]
首先感谢作者，next-terminal真心不错，难得一见的好东东！

我的next-terminal所在的机房内网还有其他几台Windows服务器，内网相互都能互联，如果我从外网登录next-terminal，不映射这些服务器，能直接填内网其他服务器的地址RDP访问嘛？

**Comment by dushixiang** [comment]
可以访问。但next-terminal目前未经过严格的安全性测试，不建议开放到公网。

**Comment by z1073** [comment]
收到！谢谢。
